/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ArffFileSampleProvider extends FileSampleProvider {
  private transient long swigCPtr;

  protected ArffFileSampleProvider(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.ArffFileSampleProvider_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ArffFileSampleProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ArffFileSampleProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArffFileSampleProvider() {
    this(jsgppJNI.new_ArffFileSampleProvider(), true);
  }

  public SampleProvider clone() {
    long cPtr = jsgppJNI.ArffFileSampleProvider_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new SampleProvider(cPtr, false);
  }

  public Dataset getNextSamples(long howMany) {
    long cPtr = jsgppJNI.ArffFileSampleProvider_getNextSamples(swigCPtr, this, howMany);
    return (cPtr == 0) ? null : new Dataset(cPtr, false);
  }

  public Dataset getAllSamples() {
    long cPtr = jsgppJNI.ArffFileSampleProvider_getAllSamples(swigCPtr, this);
    return (cPtr == 0) ? null : new Dataset(cPtr, false);
  }

  public long getDim() {
    return jsgppJNI.ArffFileSampleProvider_getDim(swigCPtr, this);
  }

  public long getNumSamples() {
    return jsgppJNI.ArffFileSampleProvider_getNumSamples(swigCPtr, this);
  }

  public void readFile(String filePath) {
    jsgppJNI.ArffFileSampleProvider_readFile(swigCPtr, this, filePath);
  }

  public void readString(String input) {
    jsgppJNI.ArffFileSampleProvider_readString(swigCPtr, this, input);
  }

}
