/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class BoundaryGridGenerator extends GridGenerator {
  private transient long swigCPtr;

  protected BoundaryGridGenerator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.BoundaryGridGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoundaryGridGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_BoundaryGridGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public BoundaryGridGenerator(GridStorage storage, long boundaryLevel) {
    this(jsgppJNI.new_BoundaryGridGenerator__SWIG_0(GridStorage.getCPtr(storage), storage, boundaryLevel), true);
  }

  public BoundaryGridGenerator(GridStorage storage) {
    this(jsgppJNI.new_BoundaryGridGenerator__SWIG_1(GridStorage.getCPtr(storage), storage), true);
  }

  public long getBoundaryLevel() {
    return jsgppJNI.BoundaryGridGenerator_getBoundaryLevel(swigCPtr, this);
  }

  public void setBoundaryLevel(long boundaryLevel) {
    jsgppJNI.BoundaryGridGenerator_setBoundaryLevel(swigCPtr, this, boundaryLevel);
  }

  public void regular(long level) {
    jsgppJNI.BoundaryGridGenerator_regular(swigCPtr, this, level);
  }

  public void cliques(long level, long clique_size) {
    jsgppJNI.BoundaryGridGenerator_cliques(swigCPtr, this, level, clique_size);
  }

  public void full(long level) {
    jsgppJNI.BoundaryGridGenerator_full(swigCPtr, this, level);
  }

  public void refine(RefinementFunctor func) {
    jsgppJNI.BoundaryGridGenerator_refine(swigCPtr, this, RefinementFunctor.getCPtr(func), func);
  }

  public long getNumberOfRefinablePoints() {
    return jsgppJNI.BoundaryGridGenerator_getNumberOfRefinablePoints(swigCPtr, this);
  }

  public void coarsen(CoarseningFunctor func, DataVector alpha) {
    jsgppJNI.BoundaryGridGenerator_coarsen(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha);
  }

  public void coarsenNFirstOnly(CoarseningFunctor func, DataVector alpha, long numFirstOnly) {
    jsgppJNI.BoundaryGridGenerator_coarsenNFirstOnly(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha, numFirstOnly);
  }

  public long getNumberOfRemovablePoints() {
    return jsgppJNI.BoundaryGridGenerator_getNumberOfRemovablePoints(swigCPtr, this);
  }

  public void refineMaxLevel(RefinementFunctor func, long maxLevel) {
    jsgppJNI.BoundaryGridGenerator_refineMaxLevel(swigCPtr, this, RefinementFunctor.getCPtr(func), func, maxLevel);
  }

  public long getNumberOfRefinablePointsToMaxLevel(long maxLevel) {
    return jsgppJNI.BoundaryGridGenerator_getNumberOfRefinablePointsToMaxLevel(swigCPtr, this, maxLevel);
  }

}
