/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class CrankNicolson extends ODESolver {
  private transient long swigCPtr;

  protected CrankNicolson(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.CrankNicolson_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CrankNicolson obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_CrankNicolson(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CrankNicolson(long nTimesteps, double timestepSize, ScreenOutput screen) {
    this(jsgppJNI.new_CrankNicolson__SWIG_0(nTimesteps, timestepSize, ScreenOutput.getCPtr(screen), screen), true);
  }

  public CrankNicolson(long nTimesteps, double timestepSize) {
    this(jsgppJNI.new_CrankNicolson__SWIG_1(nTimesteps, timestepSize), true);
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System, boolean bIdentifyLastStep, boolean verbose) {
    jsgppJNI.CrankNicolson_solve__SWIG_0(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System, bIdentifyLastStep, verbose);
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System, boolean bIdentifyLastStep) {
    jsgppJNI.CrankNicolson_solve__SWIG_1(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System, bIdentifyLastStep);
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System) {
    jsgppJNI.CrankNicolson_solve__SWIG_2(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System);
  }

}
