/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class DBMatOnlineDEChol extends DBMatOnlineDE {
  private transient long swigCPtr;

  protected DBMatOnlineDEChol(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.DBMatOnlineDEChol_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBMatOnlineDEChol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_DBMatOnlineDEChol(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DBMatOnlineDEChol(DBMatOffline offline, double beta) {
    this(jsgppJNI.new_DBMatOnlineDEChol__SWIG_0(DBMatOffline.getCPtr(offline), offline, beta), true);
  }

  public DBMatOnlineDEChol(DBMatOffline offline) {
    this(jsgppJNI.new_DBMatOnlineDEChol__SWIG_1(DBMatOffline.getCPtr(offline), offline), true);
  }

  public SizeTVector updateSystemMatrixDecomposition(long numAddedGridPoints, SWIGTYPE_p_std__listT_size_t_t deletedGridPointIndices, double lambda) {
    return new SizeTVector(jsgppJNI.DBMatOnlineDEChol_updateSystemMatrixDecomposition(swigCPtr, this, numAddedGridPoints, SWIGTYPE_p_std__listT_size_t_t.getCPtr(deletedGridPointIndices), lambda), true);
  }

}
