/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class DBMatOfflineGE extends DBMatOffline {
  private transient long swigCPtr;

  protected DBMatOfflineGE(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.DBMatOfflineGE_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBMatOfflineGE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_DBMatOfflineGE(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void buildMatrix() {
    jsgppJNI.DBMatOfflineGE_buildMatrix(swigCPtr, this);
  }

}
