/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class DensityEstimationTypeParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DensityEstimationTypeParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DensityEstimationTypeParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_DensityEstimationTypeParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static DensityEstimationType parse(String input) {
    return DensityEstimationType.swigToEnum(jsgppJNI.DensityEstimationTypeParser_parse(input));
  }

  public static String toString(DensityEstimationType type) {
    return jsgppJNI.DensityEstimationTypeParser_toString(type.swigValue());
  }

  public DensityEstimationTypeParser() {
    this(jsgppJNI.new_DensityEstimationTypeParser(), true);
  }

}
