/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class DensityEstimationConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected DensityEstimationConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DensityEstimationConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_DensityEstimationConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType_(DensityEstimationType value) {
    jsgppJNI.DensityEstimationConfiguration_type__set(swigCPtr, this, value.swigValue());
  }

  public DensityEstimationType getType_() {
    return DensityEstimationType.swigToEnum(jsgppJNI.DensityEstimationConfiguration_type__get(swigCPtr, this));
  }

  public void setDecomposition_(MatrixDecompositionType value) {
    jsgppJNI.DensityEstimationConfiguration_decomposition__set(swigCPtr, this, value.swigValue());
  }

  public MatrixDecompositionType getDecomposition_() {
    return MatrixDecompositionType.swigToEnum(jsgppJNI.DensityEstimationConfiguration_decomposition__get(swigCPtr, this));
  }

  public void setICholSweepsDecompose_(long value) {
    jsgppJNI.DensityEstimationConfiguration_iCholSweepsDecompose__set(swigCPtr, this, value);
  }

  public long getICholSweepsDecompose_() {
    return jsgppJNI.DensityEstimationConfiguration_iCholSweepsDecompose__get(swigCPtr, this);
  }

  public void setICholSweepsRefine_(long value) {
    jsgppJNI.DensityEstimationConfiguration_iCholSweepsRefine__set(swigCPtr, this, value);
  }

  public long getICholSweepsRefine_() {
    return jsgppJNI.DensityEstimationConfiguration_iCholSweepsRefine__get(swigCPtr, this);
  }

  public void setICholSweepsUpdateLambda_(long value) {
    jsgppJNI.DensityEstimationConfiguration_iCholSweepsUpdateLambda__set(swigCPtr, this, value);
  }

  public long getICholSweepsUpdateLambda_() {
    return jsgppJNI.DensityEstimationConfiguration_iCholSweepsUpdateLambda__get(swigCPtr, this);
  }

  public void setICholSweepsSolver_(long value) {
    jsgppJNI.DensityEstimationConfiguration_iCholSweepsSolver__set(swigCPtr, this, value);
  }

  public long getICholSweepsSolver_() {
    return jsgppJNI.DensityEstimationConfiguration_iCholSweepsSolver__get(swigCPtr, this);
  }

  public DensityEstimationConfiguration() {
    this(jsgppJNI.new_DensityEstimationConfiguration(), true);
  }

}
