/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class FileSampleProvider extends SampleProvider {
  private transient long swigCPtr;

  protected FileSampleProvider(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.FileSampleProvider_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileSampleProvider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_FileSampleProvider(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public long getNumSamples() {
    return jsgppJNI.FileSampleProvider_getNumSamples(swigCPtr, this);
  }

  public void readFile(String filePath) {
    jsgppJNI.FileSampleProvider_readFile(swigCPtr, this, filePath);
  }

  public void readString(String input) {
    jsgppJNI.FileSampleProvider_readString(swigCPtr, this, input);
  }

}
