/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class FileSampleDecorator extends FileSampleProvider {
  private transient long swigCPtr;

  protected FileSampleDecorator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.FileSampleDecorator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileSampleDecorator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_FileSampleDecorator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public FileSampleDecorator __assign__(FileSampleDecorator rhs) {
    return new FileSampleDecorator(jsgppJNI.FileSampleDecorator___assign__(swigCPtr, this, FileSampleDecorator.getCPtr(rhs), rhs), false);
  }

  public Dataset getNextSamples(long howMany) {
    long cPtr = jsgppJNI.FileSampleDecorator_getNextSamples(swigCPtr, this, howMany);
    return (cPtr == 0) ? null : new Dataset(cPtr, false);
  }

  public Dataset getAllSamples() {
    long cPtr = jsgppJNI.FileSampleDecorator_getAllSamples(swigCPtr, this);
    return (cPtr == 0) ? null : new Dataset(cPtr, false);
  }

  public long getDim() {
    return jsgppJNI.FileSampleDecorator_getDim(swigCPtr, this);
  }

  public long getNumSamples() {
    return jsgppJNI.FileSampleDecorator_getNumSamples(swigCPtr, this);
  }

  public void readFile(String fileName) {
    jsgppJNI.FileSampleDecorator_readFile(swigCPtr, this, fileName);
  }

  public void readString(String input) {
    jsgppJNI.FileSampleDecorator_readString(swigCPtr, this, input);
  }

}
