/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public final class FitterType {
  public final static FitterType RegressionLeastSquares = new FitterType("RegressionLeastSquares");
  public final static FitterType DensityEstimation = new FitterType("DensityEstimation");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static FitterType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + FitterType.class + " with value " + swigValue);
  }

  private FitterType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private FitterType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private FitterType(String swigName, FitterType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static FitterType[] swigValues = { RegressionLeastSquares, DensityEstimation };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

