/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class FloatVector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FloatVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_FloatVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public FloatVector() {
    this(jsgppJNI.new_FloatVector__SWIG_0(), true);
  }

  public FloatVector(long n) {
    this(jsgppJNI.new_FloatVector__SWIG_1(n), true);
  }

  public long size() {
    return jsgppJNI.FloatVector_size(swigCPtr, this);
  }

  public long capacity() {
    return jsgppJNI.FloatVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    jsgppJNI.FloatVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return jsgppJNI.FloatVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    jsgppJNI.FloatVector_clear(swigCPtr, this);
  }

  public void add(float x) {
    jsgppJNI.FloatVector_add(swigCPtr, this, x);
  }

  public float get(int i) {
    return jsgppJNI.FloatVector_get(swigCPtr, this, i);
  }

  public void set(int i, float val) {
    jsgppJNI.FloatVector_set(swigCPtr, this, i, val);
  }

}
