/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class GridPrinter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GridPrinter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridPrinter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_GridPrinter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GridPrinter(Grid SparseGrid) {
    this(jsgppJNI.new_GridPrinter(Grid.getCPtr(SparseGrid), SparseGrid), true);
  }

  public void printLevelIndexGrid(String tFilename) {
    jsgppJNI.GridPrinter_printLevelIndexGrid(swigCPtr, this, tFilename);
  }

  public void printGrid(DataVector alpha, String tFilename, long PointsPerDimension) {
    jsgppJNI.GridPrinter_printGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, PointsPerDimension);
  }

  public void printGridDomain(DataVector alpha, String tFilename, BoundingBox GridArea, long PointsPerDimension) {
    jsgppJNI.GridPrinter_printGridDomain(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, BoundingBox.getCPtr(GridArea), GridArea, PointsPerDimension);
  }

  public void printSparseGrid(DataVector alpha, String tFilename, boolean bSurplus) {
    jsgppJNI.GridPrinter_printSparseGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, bSurplus);
  }

  public void printSparseGridExpTransform(DataVector alpha, String tFilename, boolean bSurplus) {
    jsgppJNI.GridPrinter_printSparseGridExpTransform(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, bSurplus);
  }

}
