/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class GridStorage {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GridStorage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridStorage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_GridStorage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public GridStorage(long dimension) {
    this(jsgppJNI.new_GridStorage__SWIG_0(dimension), true);
  }

  public GridStorage(BoundingBox creationBoundingBox) {
    this(jsgppJNI.new_GridStorage__SWIG_1(BoundingBox.getCPtr(creationBoundingBox), creationBoundingBox), true);
  }

  public GridStorage(Stretching creationStretching) {
    this(jsgppJNI.new_GridStorage__SWIG_2(Stretching.getCPtr(creationStretching), creationStretching), true);
  }

  public GridStorage(SWIGTYPE_p_std__string istr) {
    this(jsgppJNI.new_GridStorage__SWIG_3(SWIGTYPE_p_std__string.getCPtr(istr)), true);
  }

  public GridStorage(SWIGTYPE_p_std__istream istream) {
    this(jsgppJNI.new_GridStorage__SWIG_4(SWIGTYPE_p_std__istream.getCPtr(istream)), true);
  }

  public GridStorage(GridStorage copyFrom) {
    this(jsgppJNI.new_GridStorage__SWIG_5(GridStorage.getCPtr(copyFrom), copyFrom), true);
  }

  public void operatorAssignment(GridStorage other) {
    jsgppJNI.GridStorage_operatorAssignment(swigCPtr, this, GridStorage.getCPtr(other), other);
  }

  public void clear() {
    jsgppJNI.GridStorage_clear(swigCPtr, this);
  }

  public SizeTVector deletePoints(SWIGTYPE_p_std__listT_size_t_t removePoints) {
    return new SizeTVector(jsgppJNI.GridStorage_deletePoints(swigCPtr, this, SWIGTYPE_p_std__listT_size_t_t.getCPtr(removePoints)), true);
  }

  public void unserializeNoAlgoDims(SWIGTYPE_p_std__string istr) {
    jsgppJNI.GridStorage_unserializeNoAlgoDims(swigCPtr, this, SWIGTYPE_p_std__string.getCPtr(istr));
  }

  public String serialize(int version) {
    return jsgppJNI.GridStorage_serialize__SWIG_0(swigCPtr, this, version);
  }

  public String serialize() {
    return jsgppJNI.GridStorage_serialize__SWIG_1(swigCPtr, this);
  }

  public void serialize(SWIGTYPE_p_std__ostream ostream, int version) {
    jsgppJNI.GridStorage_serialize__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostream), version);
  }

  public void serialize(SWIGTYPE_p_std__ostream ostream) {
    jsgppJNI.GridStorage_serialize__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostream));
  }

  public String toString() {
    return jsgppJNI.GridStorage_toString__SWIG_0(swigCPtr, this);
  }

  public void toString(SWIGTYPE_p_std__ostream stream) {
    jsgppJNI.GridStorage_toString__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(stream));
  }

  public long getSize() {
    return jsgppJNI.GridStorage_getSize(swigCPtr, this);
  }

  public long getNumberOfInnerPoints() {
    return jsgppJNI.GridStorage_getNumberOfInnerPoints(swigCPtr, this);
  }

  public long getDimension() {
    return jsgppJNI.GridStorage_getDimension(swigCPtr, this);
  }

  public GridPoint getPoint(long seq) {
    return new GridPoint(jsgppJNI.GridStorage_getPoint(swigCPtr, this, seq), false);
  }

  public long insert(GridPoint index) {
    return jsgppJNI.GridStorage_insert(swigCPtr, this, GridPoint.getCPtr(index), index);
  }

  public void update(GridPoint index, long pos) {
    jsgppJNI.GridStorage_update(swigCPtr, this, GridPoint.getCPtr(index), index, pos);
  }

  public void deleteLast() {
    jsgppJNI.GridStorage_deleteLast(swigCPtr, this);
  }

  public GridPoint create(GridPoint index) {
    long cPtr = jsgppJNI.GridStorage_create(swigCPtr, this, GridPoint.getCPtr(index), index);
    return (cPtr == 0) ? null : new GridPoint(cPtr, false);
  }

  public void destroy(GridPoint index) {
    jsgppJNI.GridStorage_destroy(swigCPtr, this, GridPoint.getCPtr(index), index);
  }

  public long store(GridPoint index) {
    return jsgppJNI.GridStorage_store(swigCPtr, this, GridPoint.getCPtr(index), index);
  }

  public SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator find(GridPoint index) {
    return new SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator(jsgppJNI.GridStorage_find(swigCPtr, this, GridPoint.getCPtr(index), index), true);
  }

  public SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator begin() {
    return new SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator(jsgppJNI.GridStorage_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator end() {
    return new SWIGTYPE_p_std__unordered_mapT_sgpp__base__HashGridPoint_p_size_t_sgpp__base__HashGridPointPointerHashFunctor_sgpp__base__HashGridPointPointerEqualityFunctor_t__iterator(jsgppJNI.GridStorage_end(swigCPtr, this), true);
  }

  public boolean isContaining(GridPoint index) {
    return jsgppJNI.GridStorage_isContaining(swigCPtr, this, GridPoint.getCPtr(index), index);
  }

  public long getSequenceNumber(GridPoint index) {
    return jsgppJNI.GridStorage_getSequenceNumber(swigCPtr, this, GridPoint.getCPtr(index), index);
  }

  public boolean isInvalidSequenceNumber(long s) {
    return jsgppJNI.GridStorage_isInvalidSequenceNumber(swigCPtr, this, s);
  }

  public SizeTVector getAlgorithmicDimensions() {
    return new SizeTVector(jsgppJNI.GridStorage_getAlgorithmicDimensions(swigCPtr, this), true);
  }

  public void setAlgorithmicDimensions(SizeTVector newAlgoDims) {
    jsgppJNI.GridStorage_setAlgorithmicDimensions(swigCPtr, this, SizeTVector.getCPtr(newAlgoDims), newAlgoDims);
  }

  public void recalcLeafProperty() {
    jsgppJNI.GridStorage_recalcLeafProperty(swigCPtr, this);
  }

  public BoundingBox getBoundingBox() {
    long cPtr = jsgppJNI.GridStorage_getBoundingBox(swigCPtr, this);
    return (cPtr == 0) ? null : new BoundingBox(cPtr, false);
  }

  public Stretching getStretching() {
    long cPtr = jsgppJNI.GridStorage_getStretching(swigCPtr, this);
    return (cPtr == 0) ? null : new Stretching(cPtr, false);
  }

  public void setBoundingBox(BoundingBox boundingBox) {
    jsgppJNI.GridStorage_setBoundingBox(swigCPtr, this, BoundingBox.getCPtr(boundingBox), boundingBox);
  }

  public void setStretching(Stretching stretching) {
    jsgppJNI.GridStorage_setStretching(swigCPtr, this, Stretching.getCPtr(stretching), stretching);
  }

  public void getLevelIndexArraysForEval(DataMatrix level, DataMatrix index) {
    jsgppJNI.GridStorage_getLevelIndexArraysForEval__SWIG_0(swigCPtr, this, DataMatrix.getCPtr(level), level, DataMatrix.getCPtr(index), index);
  }

  public void getLevelIndexArraysForEval(DataMatrixSP level, DataMatrixSP index) {
    jsgppJNI.GridStorage_getLevelIndexArraysForEval__SWIG_1(swigCPtr, this, DataMatrixSP.getCPtr(level), level, DataMatrixSP.getCPtr(index), index);
  }

  public void getLevelForIntegral(DataMatrix level) {
    jsgppJNI.GridStorage_getLevelForIntegral(swigCPtr, this, DataMatrix.getCPtr(level), level);
  }

  public long getMaxLevel() {
    return jsgppJNI.GridStorage_getMaxLevel(swigCPtr, this);
  }

  public void getLevelIndexMaskArraysForModEval(DataMatrix level, DataMatrix index, DataMatrix mask, DataMatrix offset) {
    jsgppJNI.GridStorage_getLevelIndexMaskArraysForModEval__SWIG_0(swigCPtr, this, DataMatrix.getCPtr(level), level, DataMatrix.getCPtr(index), index, DataMatrix.getCPtr(mask), mask, DataMatrix.getCPtr(offset), offset);
  }

  public void getLevelIndexMaskArraysForModEval(DataMatrixSP level, DataMatrixSP index, DataMatrixSP mask, DataMatrixSP offset) {
    jsgppJNI.GridStorage_getLevelIndexMaskArraysForModEval__SWIG_1(swigCPtr, this, DataMatrixSP.getCPtr(level), level, DataMatrixSP.getCPtr(index), index, DataMatrixSP.getCPtr(mask), mask, DataMatrixSP.getCPtr(offset), offset);
  }

  public double getCoordinate(GridPoint point, long d) {
    return jsgppJNI.GridStorage_getCoordinate(swigCPtr, this, GridPoint.getCPtr(point), point, d);
  }

  public double getUnitCoordinate(GridPoint point, long d) {
    return jsgppJNI.GridStorage_getUnitCoordinate(swigCPtr, this, GridPoint.getCPtr(point), point, d);
  }

  public void getCoordinates(GridPoint point, DataVector coordinates) {
    jsgppJNI.GridStorage_getCoordinates__SWIG_0(swigCPtr, this, GridPoint.getCPtr(point), point, DataVector.getCPtr(coordinates), coordinates);
  }

  public DataVector getCoordinates(GridPoint point) {
    return new DataVector(jsgppJNI.GridStorage_getCoordinates__SWIG_1(swigCPtr, this, GridPoint.getCPtr(point), point), true);
  }

}
