/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class HashGridPointPointerEqualityFunctor {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected HashGridPointPointerEqualityFunctor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HashGridPointPointerEqualityFunctor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_HashGridPointPointerEqualityFunctor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public long operatorParentheses(GridPoint s1, GridPoint s2) {
    return jsgppJNI.HashGridPointPointerEqualityFunctor_operatorParentheses(swigCPtr, this, GridPoint.getCPtr(s1), s1, GridPoint.getCPtr(s2), s2);
  }

  public HashGridPointPointerEqualityFunctor() {
    this(jsgppJNI.new_HashGridPointPointerEqualityFunctor(), true);
  }

}
