/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ImpurityRefinement_refinement_key extends AbstractRefinement_refinement_key {
  private transient long swigCPtr;

  protected ImpurityRefinement_refinement_key(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.ImpurityRefinement_refinement_key_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImpurityRefinement_refinement_key obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ImpurityRefinement_refinement_key(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ImpurityRefinement_refinement_key(GridPoint point, long seq, long dim) {
    this(jsgppJNI.new_ImpurityRefinement_refinement_key(GridPoint.getCPtr(point), point, seq, dim), true);
  }

  public long getDim() {
    return jsgppJNI.ImpurityRefinement_refinement_key_getDim(swigCPtr, this);
  }

}
