/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class IndexValPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected IndexValPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IndexValPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_IndexValPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IndexValPair() {
    this(jsgppJNI.new_IndexValPair__SWIG_0(), true);
  }

  public IndexValPair(long first, double second) {
    this(jsgppJNI.new_IndexValPair__SWIG_1(first, second), true);
  }

  public IndexValPair(IndexValPair p) {
    this(jsgppJNI.new_IndexValPair__SWIG_2(IndexValPair.getCPtr(p), p), true);
  }

  public void setFirst(long value) {
    jsgppJNI.IndexValPair_first_set(swigCPtr, this, value);
  }

  public long getFirst() {
    return jsgppJNI.IndexValPair_first_get(swigCPtr, this);
  }

  public void setSecond(double value) {
    jsgppJNI.IndexValPair_second_set(swigCPtr, this, value);
  }

  public double getSecond() {
    return jsgppJNI.IndexValPair_second_get(swigCPtr, this);
  }

}
