/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class MinerFactory {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected MinerFactory(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MinerFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_MinerFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SparseGridMiner buildMiner(String path) {
    long cPtr = jsgppJNI.MinerFactory_buildMiner(swigCPtr, this, path);
    return (cPtr == 0) ? null : new SparseGridMiner(cPtr, false);
  }

}
