/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class MSE extends Metric {
  private transient long swigCPtr;

  protected MSE(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.MSE_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MSE obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_MSE(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Metric clone() {
    long cPtr = jsgppJNI.MSE_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new Metric(cPtr, false);
  }

  public double measure(DataVector predictedValues, DataVector trueValues) {
    return jsgppJNI.MSE_measure(swigCPtr, this, DataVector.getCPtr(predictedValues), predictedValues, DataVector.getCPtr(trueValues), trueValues);
  }

  public MSE() {
    this(jsgppJNI.new_MSE(), true);
  }

}
