/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ODESolver extends SGSolver {
  private transient long swigCPtr;

  protected ODESolver(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.ODESolver_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ODESolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ODESolver(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System, boolean bIdentifyLastStep, boolean verbose) {
    jsgppJNI.ODESolver_solve__SWIG_0(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System, bIdentifyLastStep, verbose);
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System, boolean bIdentifyLastStep) {
    jsgppJNI.ODESolver_solve__SWIG_1(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System, bIdentifyLastStep);
  }

  public void solve(SLESolver LinearSystemSolver, OperationParabolicPDESolverSystem System) {
    jsgppJNI.ODESolver_solve__SWIG_2(swigCPtr, this, SLESolver.getCPtr(LinearSystemSolver), LinearSystemSolver, OperationParabolicPDESolverSystem.getCPtr(System), System);
  }

}
