/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationMatrixLTwoDotExplicitPeriodic extends OperationMatrix {
  private transient long swigCPtr;

  protected OperationMatrixLTwoDotExplicitPeriodic(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OperationMatrixLTwoDotExplicitPeriodic_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationMatrixLTwoDotExplicitPeriodic obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationMatrixLTwoDotExplicitPeriodic(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OperationMatrixLTwoDotExplicitPeriodic(DataMatrix m, Grid grid) {
    this(jsgppJNI.new_OperationMatrixLTwoDotExplicitPeriodic__SWIG_0(DataMatrix.getCPtr(m), m, Grid.getCPtr(grid), grid), true);
  }

  public OperationMatrixLTwoDotExplicitPeriodic(Grid grid) {
    this(jsgppJNI.new_OperationMatrixLTwoDotExplicitPeriodic__SWIG_1(Grid.getCPtr(grid), grid), true);
  }

  public void mult(DataVector alpha, DataVector result) {
    jsgppJNI.OperationMatrixLTwoDotExplicitPeriodic_mult(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataVector.getCPtr(result), result);
  }

}
