/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationQuadratureMC extends OperationQuadrature {
  private transient long swigCPtr;

  protected OperationQuadratureMC(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OperationQuadratureMC_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationQuadratureMC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationQuadratureMC(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OperationQuadratureMC(Grid grid, int mcPaths) {
    this(jsgppJNI.new_OperationQuadratureMC(Grid.getCPtr(grid), grid, mcPaths), true);
  }

  public double doQuadrature(DataVector alpha) {
    return jsgppJNI.OperationQuadratureMC_doQuadrature(swigCPtr, this, DataVector.getCPtr(alpha), alpha);
  }

  public double doQuadratureFunc(SWIGTYPE_p_f_int_p_double_p_void__double func, SWIGTYPE_p_void clientdata) {
    return jsgppJNI.OperationQuadratureMC_doQuadratureFunc(swigCPtr, this, SWIGTYPE_p_f_int_p_double_p_void__double.getCPtr(func), SWIGTYPE_p_void.getCPtr(clientdata));
  }

  public double doQuadratureL2Error(SWIGTYPE_p_f_int_p_double_p_void__double func, SWIGTYPE_p_void clientdata, DataVector alpha) {
    return jsgppJNI.OperationQuadratureMC_doQuadratureL2Error(swigCPtr, this, SWIGTYPE_p_f_int_p_double_p_void__double.getCPtr(func), SWIGTYPE_p_void.getCPtr(clientdata), DataVector.getCPtr(alpha), alpha);
  }

}
