/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationHierarchisation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OperationHierarchisation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationHierarchisation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationHierarchisation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void doHierarchisation(DataVector node_values) {
    jsgppJNI.OperationHierarchisation_doHierarchisation(swigCPtr, this, DataVector.getCPtr(node_values), node_values);
  }

  public void doDehierarchisation(DataVector alpha) {
    jsgppJNI.OperationHierarchisation_doDehierarchisation(swigCPtr, this, DataVector.getCPtr(alpha), alpha);
  }

}
