/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationParabolicPDESolverSystemFreeBoundaries extends OperationParabolicPDESolverSystem {
  private transient long swigCPtr;

  protected OperationParabolicPDESolverSystemFreeBoundaries(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OperationParabolicPDESolverSystemFreeBoundaries_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationParabolicPDESolverSystemFreeBoundaries obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationParabolicPDESolverSystemFreeBoundaries(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void mult(DataVector alpha, DataVector result) {
    jsgppJNI.OperationParabolicPDESolverSystemFreeBoundaries_mult(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataVector.getCPtr(result), result);
  }

  public DataVector generateRHS() {
    long cPtr = jsgppJNI.OperationParabolicPDESolverSystemFreeBoundaries_generateRHS(swigCPtr, this);
    return (cPtr == 0) ? null : new DataVector(cPtr, false);
  }

  public DataVector getGridCoefficientsForCG() {
    long cPtr = jsgppJNI.OperationParabolicPDESolverSystemFreeBoundaries_getGridCoefficientsForCG(swigCPtr, this);
    return (cPtr == 0) ? null : new DataVector(cPtr, false);
  }

}
