/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationRosenblattTransformation {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OperationRosenblattTransformation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationRosenblattTransformation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationRosenblattTransformation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void doTransformation(DataVector alpha, DataMatrix points, DataMatrix pointscdf) {
    jsgppJNI.OperationRosenblattTransformation_doTransformation__SWIG_0(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataMatrix.getCPtr(points), points, DataMatrix.getCPtr(pointscdf), pointscdf);
  }

  public void doTransformation(DataVector alpha, DataMatrix points, DataMatrix pointscdf, long dim_start) {
    jsgppJNI.OperationRosenblattTransformation_doTransformation__SWIG_1(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataMatrix.getCPtr(points), points, DataMatrix.getCPtr(pointscdf), pointscdf, dim_start);
  }

}
