/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationEvalHessian {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OperationEvalHessian(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationEvalHessian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationEvalHessian(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double evalHessian(DataVector alpha, DataVector point, DataVector gradient, DataMatrix hessian) {
    return jsgppJNI.OperationEvalHessian_evalHessian__SWIG_0(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataVector.getCPtr(point), point, DataVector.getCPtr(gradient), gradient, DataMatrix.getCPtr(hessian), hessian);
  }

  public void evalHessian(DataMatrix alpha, DataVector point, DataVector value, DataMatrix gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t hessian) {
    jsgppJNI.OperationEvalHessian_evalHessian__SWIG_1(swigCPtr, this, DataMatrix.getCPtr(alpha), alpha, DataVector.getCPtr(point), point, DataVector.getCPtr(value), value, DataMatrix.getCPtr(gradient), gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t.getCPtr(hessian));
  }

  public void setPointInUnitCube(DataVector value) {
    jsgppJNI.OperationEvalHessian_pointInUnitCube_set(swigCPtr, this, DataVector.getCPtr(value), value);
  }

  public DataVector getPointInUnitCube() {
    long cPtr = jsgppJNI.OperationEvalHessian_pointInUnitCube_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DataVector(cPtr, false);
  }

}
