/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptAdaptiveGradientDescent extends OptUnconstrainedOptimizer {
  private transient long swigCPtr;

  protected OptAdaptiveGradientDescent(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptAdaptiveGradientDescent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptAdaptiveGradientDescent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptAdaptiveGradientDescent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double stepSizeIncreaseFactor, double stepSizeDecreaseFactor, double lineSearchAccuracy) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_0(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, stepSizeIncreaseFactor, stepSizeDecreaseFactor, lineSearchAccuracy), true);
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double stepSizeIncreaseFactor, double stepSizeDecreaseFactor) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_1(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, stepSizeIncreaseFactor, stepSizeDecreaseFactor), true);
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double stepSizeIncreaseFactor) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_2(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, stepSizeIncreaseFactor), true);
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_3(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance), true);
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_4(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount), true);
  }

  public OptAdaptiveGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_5(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient), true);
  }

  public OptAdaptiveGradientDescent(OptAdaptiveGradientDescent other) {
    this(jsgppJNI.new_OptAdaptiveGradientDescent__SWIG_6(OptAdaptiveGradientDescent.getCPtr(other), other), true);
  }

  public void optimize() {
    jsgppJNI.OptAdaptiveGradientDescent_optimize(swigCPtr, this);
  }

  public OptScalarFunctionGradient getObjectiveGradient() {
    return new OptScalarFunctionGradient(jsgppJNI.OptAdaptiveGradientDescent_getObjectiveGradient(swigCPtr, this), false);
  }

  public double getTolerance() {
    return jsgppJNI.OptAdaptiveGradientDescent_getTolerance(swigCPtr, this);
  }

  public void setTolerance(double tolerance) {
    jsgppJNI.OptAdaptiveGradientDescent_setTolerance(swigCPtr, this, tolerance);
  }

  public double getStepSizeIncreaseFactor() {
    return jsgppJNI.OptAdaptiveGradientDescent_getStepSizeIncreaseFactor(swigCPtr, this);
  }

  public void setStepSizeIncreaseFactor(double stepSizeIncreaseFactor) {
    jsgppJNI.OptAdaptiveGradientDescent_setStepSizeIncreaseFactor(swigCPtr, this, stepSizeIncreaseFactor);
  }

  public double getStepSizeDecreaseFactor() {
    return jsgppJNI.OptAdaptiveGradientDescent_getStepSizeDecreaseFactor(swigCPtr, this);
  }

  public void setStepSizeDecreaseFactor(double stepSizeDecreaseFactor) {
    jsgppJNI.OptAdaptiveGradientDescent_setStepSizeDecreaseFactor(swigCPtr, this, stepSizeDecreaseFactor);
  }

  public double getLineSearchAccuracy() {
    return jsgppJNI.OptAdaptiveGradientDescent_getLineSearchAccuracy(swigCPtr, this);
  }

  public void setLineSearchAccuracy(double lineSearchAccuracy) {
    jsgppJNI.OptAdaptiveGradientDescent_setLineSearchAccuracy(swigCPtr, this, lineSearchAccuracy);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t clone) {
    jsgppJNI.OptAdaptiveGradientDescent_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t.getCPtr(clone));
  }

  public final static double DEFAULT_TOLERANCE = jsgppJNI.OptAdaptiveGradientDescent_DEFAULT_TOLERANCE_get();
  public final static double DEFAULT_STEP_SIZE_INCREASE_FACTOR = jsgppJNI.OptAdaptiveGradientDescent_DEFAULT_STEP_SIZE_INCREASE_FACTOR_get();
  public final static double DEFAULT_STEP_SIZE_DECREASE_FACTOR = jsgppJNI.OptAdaptiveGradientDescent_DEFAULT_STEP_SIZE_DECREASE_FACTOR_get();
  public final static double DEFAULT_LINE_SEARCH_ACCURACY = jsgppJNI.OptAdaptiveGradientDescent_DEFAULT_LINE_SEARCH_ACCURACY_get();
}
