/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptAutoSLESolver extends OptSLESolver {
  private transient long swigCPtr;

  protected OptAutoSLESolver(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptAutoSLESolver_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptAutoSLESolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptAutoSLESolver(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean solve(OptSLE system, DataVector b, DataVector x) {
    return jsgppJNI.OptAutoSLESolver_solve__SWIG_0(swigCPtr, this, OptSLE.getCPtr(system), system, DataVector.getCPtr(b), b, DataVector.getCPtr(x), x);
  }

  public boolean solve(OptSLE system, DataMatrix B, DataMatrix X) {
    return jsgppJNI.OptAutoSLESolver_solve__SWIG_1(swigCPtr, this, OptSLE.getCPtr(system), system, DataMatrix.getCPtr(B), B, DataMatrix.getCPtr(X), X);
  }

  public OptAutoSLESolver() {
    this(jsgppJNI.new_OptAutoSLESolver(), true);
  }

  public final static long MAX_DIM_FOR_FULL = jsgppJNI.OptAutoSLESolver_MAX_DIM_FOR_FULL_get();
  public final static long MAX_DIM_FOR_GAUSSIAN = jsgppJNI.OptAutoSLESolver_MAX_DIM_FOR_GAUSSIAN_get();
  public final static double MAX_NNZ_RATIO_FOR_SPARSE = jsgppJNI.OptAutoSLESolver_MAX_NNZ_RATIO_FOR_SPARSE_get();
  public final static double ESTIMATE_NNZ_ROWS_SAMPLE_SIZE = jsgppJNI.OptAutoSLESolver_ESTIMATE_NNZ_ROWS_SAMPLE_SIZE_get();
}
