/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptComponentScalarFunction extends OptScalarFunction {
  private transient long swigCPtr;

  protected OptComponentScalarFunction(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptComponentScalarFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptComponentScalarFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptComponentScalarFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptComponentScalarFunction(OptScalarFunction f, DoubleVector defaultValues) {
    this(jsgppJNI.new_OptComponentScalarFunction__SWIG_0(OptScalarFunction.getCPtr(f), f, DoubleVector.getCPtr(defaultValues), defaultValues), true);
  }

  public OptComponentScalarFunction(OptScalarFunction f) {
    this(jsgppJNI.new_OptComponentScalarFunction__SWIG_1(OptScalarFunction.getCPtr(f), f), true);
  }

  public OptComponentScalarFunction(OptVectorFunction f, long k, DoubleVector defaultValues) {
    this(jsgppJNI.new_OptComponentScalarFunction__SWIG_2(OptVectorFunction.getCPtr(f), f, k, DoubleVector.getCPtr(defaultValues), defaultValues), true);
  }

  public OptComponentScalarFunction(OptVectorFunction f, long k) {
    this(jsgppJNI.new_OptComponentScalarFunction__SWIG_3(OptVectorFunction.getCPtr(f), f, k), true);
  }

  public double eval(DataVector x) {
    return jsgppJNI.OptComponentScalarFunction_eval(swigCPtr, this, DataVector.getCPtr(x), x);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t clone) {
    jsgppJNI.OptComponentScalarFunction_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t.getCPtr(clone));
  }

}
