/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptGradientDescent extends OptUnconstrainedOptimizer {
  private transient long swigCPtr;

  protected OptGradientDescent(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptGradientDescent_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptGradientDescent obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptGradientDescent(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double beta, double gamma, double tolerance, double epsilon) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_0(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, beta, gamma, tolerance, epsilon), true);
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double beta, double gamma, double tolerance) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_1(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, beta, gamma, tolerance), true);
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double beta, double gamma) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_2(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, beta, gamma), true);
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double beta) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_3(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, beta), true);
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_4(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount), true);
  }

  public OptGradientDescent(OptScalarFunction f, OptScalarFunctionGradient fGradient) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_5(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient), true);
  }

  public OptGradientDescent(OptGradientDescent other) {
    this(jsgppJNI.new_OptGradientDescent__SWIG_6(OptGradientDescent.getCPtr(other), other), true);
  }

  public void optimize() {
    jsgppJNI.OptGradientDescent_optimize(swigCPtr, this);
  }

  public OptScalarFunctionGradient getObjectiveGradient() {
    return new OptScalarFunctionGradient(jsgppJNI.OptGradientDescent_getObjectiveGradient(swigCPtr, this), false);
  }

  public double getBeta() {
    return jsgppJNI.OptGradientDescent_getBeta(swigCPtr, this);
  }

  public void setBeta(double beta) {
    jsgppJNI.OptGradientDescent_setBeta(swigCPtr, this, beta);
  }

  public double getGamma() {
    return jsgppJNI.OptGradientDescent_getGamma(swigCPtr, this);
  }

  public void setGamma(double gamma) {
    jsgppJNI.OptGradientDescent_setGamma(swigCPtr, this, gamma);
  }

  public double getTolerance() {
    return jsgppJNI.OptGradientDescent_getTolerance(swigCPtr, this);
  }

  public void setTolerance(double tolerance) {
    jsgppJNI.OptGradientDescent_setTolerance(swigCPtr, this, tolerance);
  }

  public double getEpsilon() {
    return jsgppJNI.OptGradientDescent_getEpsilon(swigCPtr, this);
  }

  public void setEpsilon(double epsilon) {
    jsgppJNI.OptGradientDescent_setEpsilon(swigCPtr, this, epsilon);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t clone) {
    jsgppJNI.OptGradientDescent_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t.getCPtr(clone));
  }

  public final static long DEFAULT_MAX_IT_COUNT = jsgppJNI.OptGradientDescent_DEFAULT_MAX_IT_COUNT_get();
  public final static double DEFAULT_BETA = jsgppJNI.OptGradientDescent_DEFAULT_BETA_get();
  public final static double DEFAULT_GAMMA = jsgppJNI.OptGradientDescent_DEFAULT_GAMMA_get();
  public final static double DEFAULT_TOLERANCE = jsgppJNI.OptGradientDescent_DEFAULT_TOLERANCE_get();
  public final static double DEFAULT_EPSILON = jsgppJNI.OptGradientDescent_DEFAULT_EPSILON_get();
}
