/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptHartman3 extends OptUnconstrainedTestProblem {
  private transient long swigCPtr;

  protected OptHartman3(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptHartman3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptHartman3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptHartman3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptHartman3() {
    this(jsgppJNI.new_OptHartman3(), true);
  }

  public OptTestScalarFunction getObjectiveFunction() {
    return new OptTestScalarFunction(jsgppJNI.OptHartman3_getObjectiveFunction(swigCPtr, this), false);
  }

  public double getOptimalPointUndisplaced(DataVector x) {
    return jsgppJNI.OptHartman3_getOptimalPointUndisplaced(swigCPtr, this, DataVector.getCPtr(x), x);
  }

}
