/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptMutexType {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptMutexType(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptMutexType obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptMutexType(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void lock() {
    jsgppJNI.OptMutexType_lock(swigCPtr, this);
  }

  public void unlock() {
    jsgppJNI.OptMutexType_unlock(swigCPtr, this);
  }

  public OptMutexType() {
    this(jsgppJNI.new_OptMutexType(), true);
  }

}
