/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptRprop extends OptUnconstrainedOptimizer {
  private transient long swigCPtr;

  protected OptRprop(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptRprop_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptRprop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptRprop(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double initialStepSize, double stepSizeIncreaseFactor, double stepSizeDecreaseFactor) {
    this(jsgppJNI.new_OptRprop__SWIG_0(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, initialStepSize, stepSizeIncreaseFactor, stepSizeDecreaseFactor), true);
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double initialStepSize, double stepSizeIncreaseFactor) {
    this(jsgppJNI.new_OptRprop__SWIG_1(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, initialStepSize, stepSizeIncreaseFactor), true);
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance, double initialStepSize) {
    this(jsgppJNI.new_OptRprop__SWIG_2(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance, initialStepSize), true);
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount, double tolerance) {
    this(jsgppJNI.new_OptRprop__SWIG_3(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount, tolerance), true);
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient, long maxItCount) {
    this(jsgppJNI.new_OptRprop__SWIG_4(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient, maxItCount), true);
  }

  public OptRprop(OptScalarFunction f, OptScalarFunctionGradient fGradient) {
    this(jsgppJNI.new_OptRprop__SWIG_5(OptScalarFunction.getCPtr(f), f, OptScalarFunctionGradient.getCPtr(fGradient), fGradient), true);
  }

  public OptRprop(OptRprop other) {
    this(jsgppJNI.new_OptRprop__SWIG_6(OptRprop.getCPtr(other), other), true);
  }

  public void optimize() {
    jsgppJNI.OptRprop_optimize(swigCPtr, this);
  }

  public OptScalarFunctionGradient getObjectiveGradient() {
    return new OptScalarFunctionGradient(jsgppJNI.OptRprop_getObjectiveGradient(swigCPtr, this), false);
  }

  public double getTolerance() {
    return jsgppJNI.OptRprop_getTolerance(swigCPtr, this);
  }

  public void setTolerance(double tolerance) {
    jsgppJNI.OptRprop_setTolerance(swigCPtr, this, tolerance);
  }

  public double getInitialStepSize() {
    return jsgppJNI.OptRprop_getInitialStepSize(swigCPtr, this);
  }

  public void setInitialStepSize(double initialStepSize) {
    jsgppJNI.OptRprop_setInitialStepSize(swigCPtr, this, initialStepSize);
  }

  public double getStepSizeIncreaseFactor() {
    return jsgppJNI.OptRprop_getStepSizeIncreaseFactor(swigCPtr, this);
  }

  public void setStepSizeIncreaseFactor(double stepSizeIncreaseFactor) {
    jsgppJNI.OptRprop_setStepSizeIncreaseFactor(swigCPtr, this, stepSizeIncreaseFactor);
  }

  public double getStepSizeDecreaseFactor() {
    return jsgppJNI.OptRprop_getStepSizeDecreaseFactor(swigCPtr, this);
  }

  public void setStepSizeDecreaseFactor(double stepSizeDecreaseFactor) {
    jsgppJNI.OptRprop_setStepSizeDecreaseFactor(swigCPtr, this, stepSizeDecreaseFactor);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t clone) {
    jsgppJNI.OptRprop_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__UnconstrainedOptimizer_t.getCPtr(clone));
  }

  public final static double DEFAULT_TOLERANCE = jsgppJNI.OptRprop_DEFAULT_TOLERANCE_get();
  public final static double DEFAULT_INITIAL_STEP_SIZE = jsgppJNI.OptRprop_DEFAULT_INITIAL_STEP_SIZE_get();
  public final static double DEFAULT_STEP_SIZE_INCREASE_FACTOR = jsgppJNI.OptRprop_DEFAULT_STEP_SIZE_INCREASE_FACTOR_get();
  public final static double DEFAULT_STEP_SIZE_DECREASE_FACTOR = jsgppJNI.OptRprop_DEFAULT_STEP_SIZE_DECREASE_FACTOR_get();
}
