/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptScalarFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptScalarFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptScalarFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptScalarFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jsgppJNI.OptScalarFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jsgppJNI.OptScalarFunction_change_ownership(this, swigCPtr, true);
  }

  public OptScalarFunction(long d) {
    this(jsgppJNI.new_OptScalarFunction(d), true);
    jsgppJNI.OptScalarFunction_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double eval(DataVector x) {
    return jsgppJNI.OptScalarFunction_eval(swigCPtr, this, DataVector.getCPtr(x), x);
  }

  public long getNumberOfParameters() {
    return jsgppJNI.OptScalarFunction_getNumberOfParameters(swigCPtr, this);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t clone) {
    jsgppJNI.OptScalarFunction_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t.getCPtr(clone));
  }

}
