/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptScalarFunctionGradient {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptScalarFunctionGradient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptScalarFunctionGradient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptScalarFunctionGradient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jsgppJNI.OptScalarFunctionGradient_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jsgppJNI.OptScalarFunctionGradient_change_ownership(this, swigCPtr, true);
  }

  public OptScalarFunctionGradient(long d) {
    this(jsgppJNI.new_OptScalarFunctionGradient(d), true);
    jsgppJNI.OptScalarFunctionGradient_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public double eval(DataVector x, DataVector gradient) {
    return jsgppJNI.OptScalarFunctionGradient_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(gradient), gradient);
  }

  public long getNumberOfParameters() {
    return jsgppJNI.OptScalarFunctionGradient_getNumberOfParameters(swigCPtr, this);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionGradient_t clone) {
    jsgppJNI.OptScalarFunctionGradient_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionGradient_t.getCPtr(clone));
  }

}
