/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptUnconstrainedTestProblem {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptUnconstrainedTestProblem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptUnconstrainedTestProblem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptUnconstrainedTestProblem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OptTestScalarFunction getObjectiveFunction() {
    return new OptTestScalarFunction(jsgppJNI.OptUnconstrainedTestProblem_getObjectiveFunction(swigCPtr, this), false);
  }

  public double getOptimalPoint(DataVector x) {
    return jsgppJNI.OptUnconstrainedTestProblem_getOptimalPoint(swigCPtr, this, DataVector.getCPtr(x), x);
  }

  public double getOptimalPointUndisplaced(DataVector x) {
    return jsgppJNI.OptUnconstrainedTestProblem_getOptimalPointUndisplaced(swigCPtr, this, DataVector.getCPtr(x), x);
  }

  public void generateDisplacement() {
    jsgppJNI.OptUnconstrainedTestProblem_generateDisplacement__SWIG_0(swigCPtr, this);
  }

  public void generateDisplacement(double stdDev) {
    jsgppJNI.OptUnconstrainedTestProblem_generateDisplacement__SWIG_1(swigCPtr, this, stdDev);
  }

  public DataVector getDisplacement() {
    return new DataVector(jsgppJNI.OptUnconstrainedTestProblem_getDisplacement(swigCPtr, this), false);
  }

  public void setDisplacement(DataVector displacement) {
    jsgppJNI.OptUnconstrainedTestProblem_setDisplacement(swigCPtr, this, DataVector.getCPtr(displacement), displacement);
  }

  public final static double DEFAULT_STANDARD_DEVIATION = jsgppJNI.OptUnconstrainedTestProblem_DEFAULT_STANDARD_DEVIATION_get();
}
