/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptVectorFunctionHessian {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptVectorFunctionHessian(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptVectorFunctionHessian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptVectorFunctionHessian(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jsgppJNI.OptVectorFunctionHessian_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jsgppJNI.OptVectorFunctionHessian_change_ownership(this, swigCPtr, true);
  }

  public OptVectorFunctionHessian(long d, long m) {
    this(jsgppJNI.new_OptVectorFunctionHessian(d, m), true);
    jsgppJNI.OptVectorFunctionHessian_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void eval(DataVector x, DataVector value, DataMatrix gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t hessian) {
    jsgppJNI.OptVectorFunctionHessian_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(value), value, DataMatrix.getCPtr(gradient), gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t.getCPtr(hessian));
  }

  public long getNumberOfParameters() {
    return jsgppJNI.OptVectorFunctionHessian_getNumberOfParameters(swigCPtr, this);
  }

  public long getNumberOfComponents() {
    return jsgppJNI.OptVectorFunctionHessian_getNumberOfComponents(swigCPtr, this);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionHessian_t clone) {
    jsgppJNI.OptVectorFunctionHessian_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionHessian_t.getCPtr(clone));
  }

}
