/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptVectorFunction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptVectorFunction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptVectorFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptVectorFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    jsgppJNI.OptVectorFunction_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    jsgppJNI.OptVectorFunction_change_ownership(this, swigCPtr, true);
  }

  public OptVectorFunction(long d, long m) {
    this(jsgppJNI.new_OptVectorFunction(d, m), true);
    jsgppJNI.OptVectorFunction_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public void eval(DataVector x, DataVector value) {
    jsgppJNI.OptVectorFunction_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(value), value);
  }

  public long getNumberOfParameters() {
    return jsgppJNI.OptVectorFunction_getNumberOfParameters(swigCPtr, this);
  }

  public long getNumberOfComponents() {
    return jsgppJNI.OptVectorFunction_getNumberOfComponents(swigCPtr, this);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunction_t clone) {
    jsgppJNI.OptVectorFunction_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunction_t.getCPtr(clone));
  }

}
