/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptWrapperVectorFunctionHessian extends OptVectorFunctionHessian {
  private transient long swigCPtr;

  protected OptWrapperVectorFunctionHessian(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptWrapperVectorFunctionHessian_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptWrapperVectorFunctionHessian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptWrapperVectorFunctionHessian(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptWrapperVectorFunctionHessian(long d, long m, SWIGTYPE_p_std__functionT_void_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_R_std__vectorT_sgpp__base__DataMatrix_t_RF_t fHessian) {
    this(jsgppJNI.new_OptWrapperVectorFunctionHessian(d, m, SWIGTYPE_p_std__functionT_void_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_R_std__vectorT_sgpp__base__DataMatrix_t_RF_t.getCPtr(fHessian)), true);
  }

  public void eval(DataVector x, DataVector value, DataMatrix gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t hessian) {
    jsgppJNI.OptWrapperVectorFunctionHessian_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(value), value, DataMatrix.getCPtr(gradient), gradient, SWIGTYPE_p_std__vectorT_sgpp__base__DataMatrix_t.getCPtr(hessian));
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionHessian_t clone) {
    jsgppJNI.OptWrapperVectorFunctionHessian_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionHessian_t.getCPtr(clone));
  }

}
