/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptWrapperScalarFunctionHessian extends OptScalarFunctionHessian {
  private transient long swigCPtr;

  protected OptWrapperScalarFunctionHessian(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptWrapperScalarFunctionHessian_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptWrapperScalarFunctionHessian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptWrapperScalarFunctionHessian(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptWrapperScalarFunctionHessian(long d, SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_RF_t fHessian) {
    this(jsgppJNI.new_OptWrapperScalarFunctionHessian(d, SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_RF_t.getCPtr(fHessian)), true);
  }

  public double eval(DataVector x, DataVector gradient, DataMatrix hessian) {
    return jsgppJNI.OptWrapperScalarFunctionHessian_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(gradient), gradient, DataMatrix.getCPtr(hessian), hessian);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionHessian_t clone) {
    jsgppJNI.OptWrapperScalarFunctionHessian_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionHessian_t.getCPtr(clone));
  }

}
