/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptWrapperVectorFunctionGradient extends OptVectorFunctionGradient {
  private transient long swigCPtr;

  protected OptWrapperVectorFunctionGradient(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptWrapperVectorFunctionGradient_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptWrapperVectorFunctionGradient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptWrapperVectorFunctionGradient(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptWrapperVectorFunctionGradient(long d, long m, SWIGTYPE_p_std__functionT_void_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_RF_t fGradient) {
    this(jsgppJNI.new_OptWrapperVectorFunctionGradient(d, m, SWIGTYPE_p_std__functionT_void_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_R_sgpp__base__DataMatrix_RF_t.getCPtr(fGradient)), true);
  }

  public void eval(DataVector x, DataVector value, DataMatrix gradient) {
    jsgppJNI.OptWrapperVectorFunctionGradient_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(value), value, DataMatrix.getCPtr(gradient), gradient);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionGradient_t clone) {
    jsgppJNI.OptWrapperVectorFunctionGradient_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__VectorFunctionGradient_t.getCPtr(clone));
  }

}
