/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptWrapperScalarFunction extends OptScalarFunction {
  private transient long swigCPtr;

  protected OptWrapperScalarFunction(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptWrapperScalarFunction_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptWrapperScalarFunction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptWrapperScalarFunction(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptWrapperScalarFunction(long d, SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_RF_t f) {
    this(jsgppJNI.new_OptWrapperScalarFunction(d, SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_RF_t.getCPtr(f)), true);
  }

  public double eval(DataVector x) {
    return jsgppJNI.OptWrapperScalarFunction_eval(swigCPtr, this, DataVector.getCPtr(x), x);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t clone) {
    jsgppJNI.OptWrapperScalarFunction_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunction_t.getCPtr(clone));
  }

}
