/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class PrewaveletGridGenerator extends GridGenerator {
  private transient long swigCPtr;

  protected PrewaveletGridGenerator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.PrewaveletGridGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PrewaveletGridGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_PrewaveletGridGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public PrewaveletGridGenerator(GridStorage storage, GridStorage shadowstorage) {
    this(jsgppJNI.new_PrewaveletGridGenerator(GridStorage.getCPtr(storage), storage, GridStorage.getCPtr(shadowstorage), shadowstorage), true);
  }

  public void regular(long level) {
    jsgppJNI.PrewaveletGridGenerator_regular__SWIG_0(swigCPtr, this, level);
  }

  public void cliques(long level, long clique_size) {
    jsgppJNI.PrewaveletGridGenerator_cliques__SWIG_0(swigCPtr, this, level, clique_size);
  }

  public void regular(long level, double T) {
    jsgppJNI.PrewaveletGridGenerator_regular__SWIG_1(swigCPtr, this, level, T);
  }

  public void cliques(long level, long clique_size, double T) {
    jsgppJNI.PrewaveletGridGenerator_cliques__SWIG_1(swigCPtr, this, level, clique_size, T);
  }

  public void full(long level) {
    jsgppJNI.PrewaveletGridGenerator_full(swigCPtr, this, level);
  }

  public void refine(RefinementFunctor func) {
    jsgppJNI.PrewaveletGridGenerator_refine(swigCPtr, this, RefinementFunctor.getCPtr(func), func);
  }

  public long getNumberOfRefinablePoints() {
    return jsgppJNI.PrewaveletGridGenerator_getNumberOfRefinablePoints(swigCPtr, this);
  }

  public void coarsen(CoarseningFunctor func, DataVector alpha) {
    jsgppJNI.PrewaveletGridGenerator_coarsen(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha);
  }

  public void coarsenNFirstOnly(CoarseningFunctor func, DataVector alpha, long numFirstOnly) {
    jsgppJNI.PrewaveletGridGenerator_coarsenNFirstOnly(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha, numFirstOnly);
  }

  public long getNumberOfRemovablePoints() {
    return jsgppJNI.PrewaveletGridGenerator_getNumberOfRemovablePoints(swigCPtr, this);
  }

  public void refineMaxLevel(RefinementFunctor func, long maxLevel) {
    jsgppJNI.PrewaveletGridGenerator_refineMaxLevel(swigCPtr, this, RefinementFunctor.getCPtr(func), func, maxLevel);
  }

  public long getNumberOfRefinablePointsToMaxLevel(long maxLevel) {
    return jsgppJNI.PrewaveletGridGenerator_getNumberOfRefinablePointsToMaxLevel(swigCPtr, this, maxLevel);
  }

}
