/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class QuadRule1D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected QuadRule1D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QuadRule1D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_QuadRule1D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public QuadRule1D() {
    this(jsgppJNI.new_QuadRule1D(), true);
  }

  public long getMaxSupportedLevel() {
    return jsgppJNI.QuadRule1D_getMaxSupportedLevel(swigCPtr, this);
  }

  public void getLevelPointsAndWeights(long level, DataVector coordinates, DataVector weights) {
    jsgppJNI.QuadRule1D_getLevelPointsAndWeights(swigCPtr, this, level, DataVector.getCPtr(coordinates), coordinates, DataVector.getCPtr(weights), weights);
  }

}
