/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class RandomShufflingFunctor extends ShufflingFunctor {
  private transient long swigCPtr;

  protected RandomShufflingFunctor(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.RandomShufflingFunctor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(RandomShufflingFunctor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_RandomShufflingFunctor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ShufflingFunctor clone() {
    long cPtr = jsgppJNI.RandomShufflingFunctor_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ShufflingFunctor(cPtr, false);
  }

  public void shuffle(Dataset dataset, SizeTVector indices) {
    jsgppJNI.RandomShufflingFunctor_shuffle(swigCPtr, this, Dataset.getCPtr(dataset), dataset, SizeTVector.getCPtr(indices), indices);
  }

  public RandomShufflingFunctor() {
    this(jsgppJNI.new_RandomShufflingFunctor(), true);
  }

}
