/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SBsplineModifiedClenshawCurtisBase extends SBasis {
  private transient long swigCPtr;

  protected SBsplineModifiedClenshawCurtisBase(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SBsplineModifiedClenshawCurtisBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBsplineModifiedClenshawCurtisBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SBsplineModifiedClenshawCurtisBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SBsplineModifiedClenshawCurtisBase() {
    this(jsgppJNI.new_SBsplineModifiedClenshawCurtisBase__SWIG_0(), true);
  }

  public SBsplineModifiedClenshawCurtisBase(long degree) {
    this(jsgppJNI.new_SBsplineModifiedClenshawCurtisBase__SWIG_1(degree), true);
  }

  public double clenshawCurtisPoint(long l, long i) {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_clenshawCurtisPoint(swigCPtr, this, l, i);
  }

  public double clenshawCurtisPointNegativeIndex(long l, long ni) {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_clenshawCurtisPointNegativeIndex(swigCPtr, this, l, ni);
  }

  public double eval(long l, long i, double x) {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_eval(swigCPtr, this, l, i, x);
  }

  public double evalDx(long l, long i, double x) {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_evalDx(swigCPtr, this, l, i, x);
  }

  public double evalDxDx(long l, long i, double x) {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_evalDxDx(swigCPtr, this, l, i, x);
  }

  public long getDegree() {
    return jsgppJNI.SBsplineModifiedClenshawCurtisBase_getDegree(swigCPtr, this);
  }

}
