/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SBsplineBase extends SBasis {
  private transient long swigCPtr;

  protected SBsplineBase(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SBsplineBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SBsplineBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SBsplineBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SBsplineBase() {
    this(jsgppJNI.new_SBsplineBase__SWIG_0(), true);
  }

  public SBsplineBase(long degree) {
    this(jsgppJNI.new_SBsplineBase__SWIG_1(degree), true);
  }

  public double uniformBSpline(double x, long p) {
    return jsgppJNI.SBsplineBase_uniformBSpline(swigCPtr, this, x, p);
  }

  public double uniformBSplineDx(double x, long p) {
    return jsgppJNI.SBsplineBase_uniformBSplineDx(swigCPtr, this, x, p);
  }

  public double uniformBSplineDxDx(double x, long p) {
    return jsgppJNI.SBsplineBase_uniformBSplineDxDx(swigCPtr, this, x, p);
  }

  public double eval(long l, long i, double x) {
    return jsgppJNI.SBsplineBase_eval(swigCPtr, this, l, i, x);
  }

  public double evalDx(long l, long i, double x) {
    return jsgppJNI.SBsplineBase_evalDx(swigCPtr, this, l, i, x);
  }

  public double evalDxDx(long l, long i, double x) {
    return jsgppJNI.SBsplineBase_evalDxDx(swigCPtr, this, l, i, x);
  }

  public long getDegree() {
    return jsgppJNI.SBsplineBase_getDegree(swigCPtr, this);
  }

}
