/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ScorerShufflingTypeParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScorerShufflingTypeParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScorerShufflingTypeParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ScorerShufflingTypeParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ScorerShufflingType parse(String input) {
    return ScorerShufflingType.swigToEnum(jsgppJNI.ScorerShufflingTypeParser_parse(input));
  }

  public static String toString(ScorerShufflingType type) {
    return jsgppJNI.ScorerShufflingTypeParser_toString(type.swigValue());
  }

  public ScorerShufflingTypeParser() {
    this(jsgppJNI.new_ScorerShufflingTypeParser(), true);
  }

}
