/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public final class ScorerMetricType {
  public final static ScorerMetricType mse = new ScorerMetricType("mse");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ScorerMetricType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ScorerMetricType.class + " with value " + swigValue);
  }

  private ScorerMetricType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ScorerMetricType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ScorerMetricType(String swigName, ScorerMetricType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ScorerMetricType[] swigValues = { mse };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

