/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ScorerMetricTypeParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScorerMetricTypeParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScorerMetricTypeParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ScorerMetricTypeParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static ScorerMetricType parse(String input) {
    return ScorerMetricType.swigToEnum(jsgppJNI.ScorerMetricTypeParser_parse(input));
  }

  public static String toString(ScorerMetricType type) {
    return jsgppJNI.ScorerMetricTypeParser_toString(type.swigValue());
  }

  public ScorerMetricTypeParser() {
    this(jsgppJNI.new_ScorerMetricTypeParser(), true);
  }

}
