/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ScreenOutput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ScreenOutput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ScreenOutput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ScreenOutput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ScreenOutput() {
    this(jsgppJNI.new_ScreenOutput(), true);
  }

  public void update(long progress, String status) {
    jsgppJNI.ScreenOutput_update(swigCPtr, this, progress, status);
  }

  public void writeTitle(String appTitle, String appAuthor) {
    jsgppJNI.ScreenOutput_writeTitle(swigCPtr, this, appTitle, appAuthor);
  }

  public void writeHelp(String helpText) {
    jsgppJNI.ScreenOutput_writeHelp(swigCPtr, this, helpText);
  }

  public void writeStartSolve(String text) {
    jsgppJNI.ScreenOutput_writeStartSolve(swigCPtr, this, text);
  }

  public void writeEmptyLines(long numLines) {
    jsgppJNI.ScreenOutput_writeEmptyLines(swigCPtr, this, numLines);
  }

}
