/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SequentialShufflingFunctor extends ShufflingFunctor {
  private transient long swigCPtr;

  protected SequentialShufflingFunctor(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SequentialShufflingFunctor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SequentialShufflingFunctor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SequentialShufflingFunctor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ShufflingFunctor clone() {
    long cPtr = jsgppJNI.SequentialShufflingFunctor_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new ShufflingFunctor(cPtr, false);
  }

  public void shuffle(Dataset data, SizeTVector indices) {
    jsgppJNI.SequentialShufflingFunctor_shuffle(swigCPtr, this, Dataset.getCPtr(data), data, SizeTVector.getCPtr(indices), indices);
  }

  public SequentialShufflingFunctor() {
    this(jsgppJNI.new_SequentialShufflingFunctor(), true);
  }

}
