/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SGetAffectedBasisFunctionsBoundaries {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SGetAffectedBasisFunctionsBoundaries(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGetAffectedBasisFunctionsBoundaries obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SGetAffectedBasisFunctionsBoundaries(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SGetAffectedBasisFunctionsBoundaries(GridStorage storage) {
    this(jsgppJNI.new_SGetAffectedBasisFunctionsBoundaries(GridStorage.getCPtr(storage), storage), true);
  }

  public void operatorParentheses(SLinearBoundaryBase basis, DataVector point, IndexValVector result) {
    jsgppJNI.SGetAffectedBasisFunctionsBoundaries_operatorParentheses(swigCPtr, this, SLinearBoundaryBase.getCPtr(basis), basis, DataVector.getCPtr(point), point, IndexValVector.getCPtr(result), result);
  }

}
