/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SLESolverSPConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SLESolverSPConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SLESolverSPConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SLESolverSPConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setType_(SLESolverType value) {
    jsgppJNI.SLESolverSPConfiguration_type__set(swigCPtr, this, value.swigValue());
  }

  public SLESolverType getType_() {
    return SLESolverType.swigToEnum(jsgppJNI.SLESolverSPConfiguration_type__get(swigCPtr, this));
  }

  public void setEps_(float value) {
    jsgppJNI.SLESolverSPConfiguration_eps__set(swigCPtr, this, value);
  }

  public float getEps_() {
    return jsgppJNI.SLESolverSPConfiguration_eps__get(swigCPtr, this);
  }

  public void setMaxIterations_(long value) {
    jsgppJNI.SLESolverSPConfiguration_maxIterations__set(swigCPtr, this, value);
  }

  public long getMaxIterations_() {
    return jsgppJNI.SLESolverSPConfiguration_maxIterations__get(swigCPtr, this);
  }

  public void setThreshold_(float value) {
    jsgppJNI.SLESolverSPConfiguration_threshold__set(swigCPtr, this, value);
  }

  public float getThreshold_() {
    return jsgppJNI.SLESolverSPConfiguration_threshold__get(swigCPtr, this);
  }

  public SLESolverSPConfiguration() {
    this(jsgppJNI.new_SLESolverSPConfiguration(), true);
  }

}
