/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SplittingScorerFactory extends ScorerFactory {
  private transient long swigCPtr;

  protected SplittingScorerFactory(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SplittingScorerFactory_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SplittingScorerFactory obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SplittingScorerFactory(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SplittingScorerFactory() {
    this(jsgppJNI.new_SplittingScorerFactory(), true);
  }

  public Scorer buildScorer(SWIGTYPE_p_sgpp__datadriven__DataMiningConfigParser parser) {
    long cPtr = jsgppJNI.SplittingScorerFactory_buildScorer(swigCPtr, this, SWIGTYPE_p_sgpp__datadriven__DataMiningConfigParser.getCPtr(parser));
    return (cPtr == 0) ? null : new Scorer(cPtr, false);
  }

}
