/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SquareRootGridGenerator extends GridGenerator {
  private transient long swigCPtr;

  protected SquareRootGridGenerator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SquareRootGridGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SquareRootGridGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SquareRootGridGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SquareRootGridGenerator(GridStorage storage) {
    this(jsgppJNI.new_SquareRootGridGenerator(GridStorage.getCPtr(storage), storage), true);
  }

  public void regular(long level) {
    jsgppJNI.SquareRootGridGenerator_regular(swigCPtr, this, level);
  }

  public void cliques(long level, long clique_size) {
    jsgppJNI.SquareRootGridGenerator_cliques(swigCPtr, this, level, clique_size);
  }

  public void full(long level) {
    jsgppJNI.SquareRootGridGenerator_full(swigCPtr, this, level);
  }

  public void refine(RefinementFunctor func) {
    jsgppJNI.SquareRootGridGenerator_refine(swigCPtr, this, RefinementFunctor.getCPtr(func), func);
  }

  public long getNumberOfRefinablePoints() {
    return jsgppJNI.SquareRootGridGenerator_getNumberOfRefinablePoints(swigCPtr, this);
  }

  public void coarsen(CoarseningFunctor func, DataVector alpha) {
    jsgppJNI.SquareRootGridGenerator_coarsen(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha);
  }

  public void coarsenNFirstOnly(CoarseningFunctor func, DataVector alpha, long numFirstOnly) {
    jsgppJNI.SquareRootGridGenerator_coarsenNFirstOnly(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha, numFirstOnly);
  }

  public long getNumberOfRemovablePoints() {
    return jsgppJNI.SquareRootGridGenerator_getNumberOfRemovablePoints(swigCPtr, this);
  }

  public void refineMaxLevel(RefinementFunctor func, long maxLevel) {
    jsgppJNI.SquareRootGridGenerator_refineMaxLevel(swigCPtr, this, RefinementFunctor.getCPtr(func), func, maxLevel);
  }

  public long getNumberOfRefinablePointsToMaxLevel(long maxLevel) {
    return jsgppJNI.SquareRootGridGenerator_getNumberOfRefinablePointsToMaxLevel(swigCPtr, this, maxLevel);
  }

}
