/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class StandardGridGenerator extends GridGenerator {
  private transient long swigCPtr;

  protected StandardGridGenerator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.StandardGridGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StandardGridGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_StandardGridGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StandardGridGenerator(GridStorage storage) {
    this(jsgppJNI.new_StandardGridGenerator(GridStorage.getCPtr(storage), storage), true);
  }

  public void regular(long level) {
    jsgppJNI.StandardGridGenerator_regular__SWIG_0(swigCPtr, this, level);
  }

  public void regular(long level, double T) {
    jsgppJNI.StandardGridGenerator_regular__SWIG_1(swigCPtr, this, level, T);
  }

  public void regularInter(long level, SWIGTYPE_p_std__vectorT_std__vectorT_size_t_t_t terms, double T) {
    jsgppJNI.StandardGridGenerator_regularInter(swigCPtr, this, level, SWIGTYPE_p_std__vectorT_std__vectorT_size_t_t_t.getCPtr(terms), T);
  }

  public void cliques(long level, long clique_size) {
    jsgppJNI.StandardGridGenerator_cliques__SWIG_0(swigCPtr, this, level, clique_size);
  }

  public void cliques(long level, long clique_size, double T) {
    jsgppJNI.StandardGridGenerator_cliques__SWIG_1(swigCPtr, this, level, clique_size, T);
  }

  public void full(long level) {
    jsgppJNI.StandardGridGenerator_full(swigCPtr, this, level);
  }

  public void refine(RefinementFunctor func) {
    jsgppJNI.StandardGridGenerator_refine(swigCPtr, this, RefinementFunctor.getCPtr(func), func);
  }

  public void refineInter(RefinementFunctor func, SWIGTYPE_p_std__unordered_setT_std__vectorT_bool_t_t interactions) {
    jsgppJNI.StandardGridGenerator_refineInter__SWIG_0(swigCPtr, this, RefinementFunctor.getCPtr(func), func, SWIGTYPE_p_std__unordered_setT_std__vectorT_bool_t_t.getCPtr(interactions));
  }

  public void refineInter(RefinementFunctor func, SWIGTYPE_p_std__vectorT_std__vectorT_size_t_t_t interactions) {
    jsgppJNI.StandardGridGenerator_refineInter__SWIG_1(swigCPtr, this, RefinementFunctor.getCPtr(func), func, SWIGTYPE_p_std__vectorT_std__vectorT_size_t_t_t.getCPtr(interactions));
  }

  public long getNumberOfRefinablePoints() {
    return jsgppJNI.StandardGridGenerator_getNumberOfRefinablePoints(swigCPtr, this);
  }

  public void coarsen(CoarseningFunctor func, DataVector alpha) {
    jsgppJNI.StandardGridGenerator_coarsen(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha);
  }

  public void coarsenNFirstOnly(CoarseningFunctor func, DataVector alpha, long numFirstOnly) {
    jsgppJNI.StandardGridGenerator_coarsenNFirstOnly(swigCPtr, this, CoarseningFunctor.getCPtr(func), func, DataVector.getCPtr(alpha), alpha, numFirstOnly);
  }

  public long getNumberOfRemovablePoints() {
    return jsgppJNI.StandardGridGenerator_getNumberOfRemovablePoints(swigCPtr, this);
  }

  public void refineMaxLevel(RefinementFunctor func, long maxLevel) {
    jsgppJNI.StandardGridGenerator_refineMaxLevel(swigCPtr, this, RefinementFunctor.getCPtr(func), func, maxLevel);
  }

  public long getNumberOfRefinablePointsToMaxLevel(long maxLevel) {
    return jsgppJNI.StandardGridGenerator_getNumberOfRefinablePointsToMaxLevel(swigCPtr, this, maxLevel);
  }

}
