/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class Stretching extends BoundingBox {
  private transient long swigCPtr;

  protected Stretching(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.Stretching_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Stretching obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_Stretching(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public Stretching(long dimension) {
    this(jsgppJNI.new_Stretching__SWIG_0(dimension), true);
  }

  public Stretching(BoundingBox1DVector boundaries, Stretching1DVector stretching1Ds) {
    this(jsgppJNI.new_Stretching__SWIG_1(BoundingBox1DVector.getCPtr(boundaries), boundaries, Stretching1DVector.getCPtr(stretching1Ds), stretching1Ds), true);
  }

  public Stretching(long dimension, DoubleVector coordinates) {
    this(jsgppJNI.new_Stretching__SWIG_2(dimension, DoubleVector.getCPtr(coordinates), coordinates), true);
  }

  public double getCoordinate(long level, long index, long d) {
    return jsgppJNI.Stretching_getCoordinate(swigCPtr, this, level, index, d);
  }

  public Stretching1D getStretching1D(long d) {
    return new Stretching1D(jsgppJNI.Stretching_getStretching1D(swigCPtr, this, d), false);
  }

  public void printLookupTable() {
    jsgppJNI.Stretching_printLookupTable(swigCPtr, this);
  }

  public void getAdjacentPositions(long level, long index, long d, SWIGTYPE_p_double posc, SWIGTYPE_p_double posl, SWIGTYPE_p_double posr) {
    jsgppJNI.Stretching_getAdjacentPositions(swigCPtr, this, level, index, d, SWIGTYPE_p_double.getCPtr(posc), SWIGTYPE_p_double.getCPtr(posl), SWIGTYPE_p_double.getCPtr(posr));
  }

  public String getStretchingMode() {
    return jsgppJNI.Stretching_getStretchingMode(swigCPtr, this);
  }

  public DoubleVector getDiscreteVector(boolean bSort) {
    long cPtr = jsgppJNI.Stretching_getDiscreteVector(swigCPtr, this, bSort);
    return (cPtr == 0) ? null : new DoubleVector(cPtr, false);
  }

  public SWIGTYPE_p_std__vectorT_unsigned_int_t getDiscreteVectorLevel() {
    return new SWIGTYPE_p_std__vectorT_unsigned_int_t(jsgppJNI.Stretching_getDiscreteVectorLevel(swigCPtr, this), true);
  }

  public void calculateNeighborLookup(long maxlevel) {
    jsgppJNI.Stretching_calculateNeighborLookup(swigCPtr, this, maxlevel);
  }

  public String serialize(int version) {
    return jsgppJNI.Stretching_serialize__SWIG_0(swigCPtr, this, version);
  }

  public String serialize() {
    return jsgppJNI.Stretching_serialize__SWIG_1(swigCPtr, this);
  }

  public void serialize(SWIGTYPE_p_std__ostream ostream, int version) {
    jsgppJNI.Stretching_serialize__SWIG_2(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostream), version);
  }

  public void serialize(SWIGTYPE_p_std__ostream ostream) {
    jsgppJNI.Stretching_serialize__SWIG_3(swigCPtr, this, SWIGTYPE_p_std__ostream.getCPtr(ostream));
  }

  public void unserialize(String istr, String mode, int version) {
    jsgppJNI.Stretching_unserialize__SWIG_0(swigCPtr, this, istr, mode, version);
  }

  public void unserialize(SWIGTYPE_p_std__istream istr, String mode, int version) {
    jsgppJNI.Stretching_unserialize__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__istream.getCPtr(istr), mode, version);
  }

}
