/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SurplusVolumeRefinementFunctor extends RefinementFunctor {
  private transient long swigCPtr;

  protected SurplusVolumeRefinementFunctor(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SurplusVolumeRefinementFunctor_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SurplusVolumeRefinementFunctor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SurplusVolumeRefinementFunctor(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SurplusVolumeRefinementFunctor(DataVector alpha, long refinements_num, double threshold) {
    this(jsgppJNI.new_SurplusVolumeRefinementFunctor__SWIG_0(DataVector.getCPtr(alpha), alpha, refinements_num, threshold), true);
  }

  public SurplusVolumeRefinementFunctor(DataVector alpha, long refinements_num) {
    this(jsgppJNI.new_SurplusVolumeRefinementFunctor__SWIG_1(DataVector.getCPtr(alpha), alpha, refinements_num), true);
  }

  public SurplusVolumeRefinementFunctor(DataVector alpha) {
    this(jsgppJNI.new_SurplusVolumeRefinementFunctor__SWIG_2(DataVector.getCPtr(alpha), alpha), true);
  }

  public double operatorParentheses(GridStorage storage, long seq) {
    return jsgppJNI.SurplusVolumeRefinementFunctor_operatorParentheses(swigCPtr, this, GridStorage.getCPtr(storage), storage, seq);
  }

  public double start() {
    return jsgppJNI.SurplusVolumeRefinementFunctor_start(swigCPtr, this);
  }

  public long getRefinementsNum() {
    return jsgppJNI.SurplusVolumeRefinementFunctor_getRefinementsNum(swigCPtr, this);
  }

  public double getRefinementThreshold() {
    return jsgppJNI.SurplusVolumeRefinementFunctor_getRefinementThreshold(swigCPtr, this);
  }

}
