/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_RF_t {
  private transient long swigCPtr;

  protected SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_RF_t(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_RF_t() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_std__functionT_double_fsgpp__base__DataVector_const_R_sgpp__base__DataVector_RF_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

