/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class AbstractRefinement {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected AbstractRefinement(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(AbstractRefinement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_AbstractRefinement(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean compare_pairs(SWIGTYPE_p_std__pairT_std__shared_ptrT_sgpp__base__AbstractRefinement_refinement_key_t_double_t lhs, SWIGTYPE_p_std__pairT_std__shared_ptrT_sgpp__base__AbstractRefinement_refinement_key_t_double_t rhs) {
    return jsgppJNI.AbstractRefinement_compare_pairs(SWIGTYPE_p_std__pairT_std__shared_ptrT_sgpp__base__AbstractRefinement_refinement_key_t_double_t.getCPtr(lhs), SWIGTYPE_p_std__pairT_std__shared_ptrT_sgpp__base__AbstractRefinement_refinement_key_t_double_t.getCPtr(rhs));
  }

  public void free_refine(GridStorage storage, RefinementFunctor functor) {
    jsgppJNI.AbstractRefinement_free_refine(swigCPtr, this, GridStorage.getCPtr(storage), storage, RefinementFunctor.getCPtr(functor), functor);
  }

  public long getNumberOfRefinablePoints(GridStorage storage) {
    return jsgppJNI.AbstractRefinement_getNumberOfRefinablePoints(swigCPtr, this, GridStorage.getCPtr(storage), storage);
  }

  public void refineGridpoint1D(GridStorage storage, GridPoint point, long d) {
    jsgppJNI.AbstractRefinement_refineGridpoint1D__SWIG_0(swigCPtr, this, GridStorage.getCPtr(storage), storage, GridPoint.getCPtr(point), point, d);
  }

  public void refineGridpoint1D(GridStorage storage, long seq, long d) {
    jsgppJNI.AbstractRefinement_refineGridpoint1D__SWIG_1(swigCPtr, this, GridStorage.getCPtr(storage), storage, seq, d);
  }

  public boolean isRefinable(GridStorage storage, GridPoint point) {
    return jsgppJNI.AbstractRefinement_isRefinable(swigCPtr, this, GridStorage.getCPtr(storage), storage, GridPoint.getCPtr(point), point);
  }

  public long getIndexOfMin(SWIGTYPE_p_double array, long length) {
    return jsgppJNI.AbstractRefinement_getIndexOfMin(swigCPtr, this, SWIGTYPE_p_double.getCPtr(array), length);
  }

}
