/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class BoundingBox1D {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected BoundingBox1D(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(BoundingBox1D obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_BoundingBox1D(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setLeftBoundary(double value) {
    jsgppJNI.BoundingBox1D_leftBoundary_set(swigCPtr, this, value);
  }

  public double getLeftBoundary() {
    return jsgppJNI.BoundingBox1D_leftBoundary_get(swigCPtr, this);
  }

  public void setRightBoundary(double value) {
    jsgppJNI.BoundingBox1D_rightBoundary_set(swigCPtr, this, value);
  }

  public double getRightBoundary() {
    return jsgppJNI.BoundingBox1D_rightBoundary_get(swigCPtr, this);
  }

  public void setBDirichletLeft(boolean value) {
    jsgppJNI.BoundingBox1D_bDirichletLeft_set(swigCPtr, this, value);
  }

  public boolean getBDirichletLeft() {
    return jsgppJNI.BoundingBox1D_bDirichletLeft_get(swigCPtr, this);
  }

  public void setBDirichletRight(boolean value) {
    jsgppJNI.BoundingBox1D_bDirichletRight_set(swigCPtr, this, value);
  }

  public boolean getBDirichletRight() {
    return jsgppJNI.BoundingBox1D_bDirichletRight_get(swigCPtr, this);
  }

  public BoundingBox1D() {
    this(jsgppJNI.new_BoundingBox1D__SWIG_0(), true);
  }

  public BoundingBox1D(double leftBoundary, double rightBoundary) {
    this(jsgppJNI.new_BoundingBox1D__SWIG_1(leftBoundary, rightBoundary), true);
  }

  public BoundingBox1D(double leftBoundary, double rightBoundary, boolean bDirichletLeft, boolean bDirichletRight) {
    this(jsgppJNI.new_BoundingBox1D__SWIG_2(leftBoundary, rightBoundary, bDirichletLeft, bDirichletRight), true);
  }

}
