/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class DBMatOfflineDenseIChol extends DBMatOfflineChol {
  private transient long swigCPtr;

  protected DBMatOfflineDenseIChol(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.DBMatOfflineDenseIChol_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DBMatOfflineDenseIChol obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_DBMatOfflineDenseIChol(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DBMatOfflineDenseIChol(RegularGridConfiguration gridConfig, AdpativityConfiguration adaptivityConfig, RegularizationConfiguration regularizationConfig, DensityEstimationConfiguration densityEstimationConfig) {
    this(jsgppJNI.new_DBMatOfflineDenseIChol__SWIG_0(RegularGridConfiguration.getCPtr(gridConfig), gridConfig, AdpativityConfiguration.getCPtr(adaptivityConfig), adaptivityConfig, RegularizationConfiguration.getCPtr(regularizationConfig), regularizationConfig, DensityEstimationConfiguration.getCPtr(densityEstimationConfig), densityEstimationConfig), true);
  }

  public DBMatOfflineDenseIChol(String fileName) {
    this(jsgppJNI.new_DBMatOfflineDenseIChol__SWIG_1(fileName), true);
  }

  public DBMatOffline clone() {
    long cPtr = jsgppJNI.DBMatOfflineDenseIChol_clone(swigCPtr, this);
    return (cPtr == 0) ? null : new DBMatOffline(cPtr, false);
  }

  public void decomposeMatrix() {
    jsgppJNI.DBMatOfflineDenseIChol_decomposeMatrix(swigCPtr, this);
  }

  public void choleskyModification(long newPoints, SWIGTYPE_p_std__listT_size_t_t deletedPoints, double lambda) {
    jsgppJNI.DBMatOfflineDenseIChol_choleskyModification(swigCPtr, this, newPoints, SWIGTYPE_p_std__listT_size_t_t.getCPtr(deletedPoints), lambda);
  }

  public static void ichol(DataMatrix matrix, DataMatrix result, long sweeps, long startRow) {
    jsgppJNI.DBMatOfflineDenseIChol_ichol__SWIG_0(DataMatrix.getCPtr(matrix), matrix, DataMatrix.getCPtr(result), result, sweeps, startRow);
  }

  public static void ichol(DataMatrix matrix, DataMatrix result, long sweeps) {
    jsgppJNI.DBMatOfflineDenseIChol_ichol__SWIG_1(DataMatrix.getCPtr(matrix), matrix, DataMatrix.getCPtr(result), result, sweeps);
  }

  public static void ichol(DataMatrix matrix, DataMatrix result) {
    jsgppJNI.DBMatOfflineDenseIChol_ichol__SWIG_2(DataMatrix.getCPtr(matrix), matrix, DataMatrix.getCPtr(result), result);
  }

}
