/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class FitterTypeParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected FitterTypeParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FitterTypeParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_FitterTypeParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static FitterType parse(String input) {
    return FitterType.swigToEnum(jsgppJNI.FitterTypeParser_parse(input));
  }

  public static String toString(FitterType type) {
    return jsgppJNI.FitterTypeParser_toString(type.swigValue());
  }

  public FitterTypeParser() {
    this(jsgppJNI.new_FitterTypeParser(), true);
  }

}
