/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class GridPrinterForStretching extends GridPrinter {
  private transient long swigCPtr;

  protected GridPrinterForStretching(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.GridPrinterForStretching_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridPrinterForStretching obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_GridPrinterForStretching(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public GridPrinterForStretching(Grid SparseGrid) {
    this(jsgppJNI.new_GridPrinterForStretching(Grid.getCPtr(SparseGrid), SparseGrid), true);
  }

  public void printGrid(DataVector alpha, String tFilename, long PointsPerDimension) {
    jsgppJNI.GridPrinterForStretching_printGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, PointsPerDimension);
  }

  public void printGridDomain(DataVector alpha, String tFilename, BoundingBox GridArea, long PointsPerDimension) {
    jsgppJNI.GridPrinterForStretching_printGridDomain(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, BoundingBox.getCPtr(GridArea), GridArea, PointsPerDimension);
  }

  public void printGridDomainStretching(DataVector alpha, String tFilename, Stretching GridArea, long PointsPerDimension) {
    jsgppJNI.GridPrinterForStretching_printGridDomainStretching(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, Stretching.getCPtr(GridArea), GridArea, PointsPerDimension);
  }

  public void printSparseGrid(DataVector alpha, String tFilename, boolean bSurplus) {
    jsgppJNI.GridPrinterForStretching_printSparseGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, bSurplus);
  }

  public void printSparseGridExpTransform(DataVector alpha, String tFilename, boolean bSurplus) {
    jsgppJNI.GridPrinterForStretching_printSparseGridExpTransform(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tFilename, bSurplus);
  }

}
