/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class GridTypeParser {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected GridTypeParser(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(GridTypeParser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_GridTypeParser(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static GridType parse(String input) {
    return GridType.swigToEnum(jsgppJNI.GridTypeParser_parse(input));
  }

  public static String toString(GridType type) {
    return jsgppJNI.GridTypeParser_toString(type.swigValue());
  }

  public GridTypeParser() {
    this(jsgppJNI.new_GridTypeParser(), true);
  }

}
