/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class HeatEquationSolverWithStretching extends ParabolicPDESolver {
  private transient long swigCPtr;

  protected HeatEquationSolverWithStretching(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.HeatEquationSolverWithStretching_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(HeatEquationSolverWithStretching obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_HeatEquationSolverWithStretching(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public HeatEquationSolverWithStretching() {
    this(jsgppJNI.new_HeatEquationSolverWithStretching(), true);
  }

  public void constructGrid(Stretching myStretching, long level) {
    jsgppJNI.HeatEquationSolverWithStretching_constructGrid__SWIG_0(swigCPtr, this, Stretching.getCPtr(myStretching), myStretching, level);
  }

  public void constructGrid(BoundingBox myStretching, long level) {
    jsgppJNI.HeatEquationSolverWithStretching_constructGrid__SWIG_1(swigCPtr, this, BoundingBox.getCPtr(myStretching), myStretching, level);
  }

  public void solveExplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha, boolean verbose, boolean generateAnimation) {
    jsgppJNI.HeatEquationSolverWithStretching_solveExplicitEuler__SWIG_0(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha, verbose, generateAnimation);
  }

  public void solveExplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha, boolean verbose) {
    jsgppJNI.HeatEquationSolverWithStretching_solveExplicitEuler__SWIG_1(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha, verbose);
  }

  public void solveExplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha) {
    jsgppJNI.HeatEquationSolverWithStretching_solveExplicitEuler__SWIG_2(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha);
  }

  public void solveImplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha, boolean verbose, boolean generateAnimation) {
    jsgppJNI.HeatEquationSolverWithStretching_solveImplicitEuler__SWIG_0(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha, verbose, generateAnimation);
  }

  public void solveImplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha, boolean verbose) {
    jsgppJNI.HeatEquationSolverWithStretching_solveImplicitEuler__SWIG_1(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha, verbose);
  }

  public void solveImplicitEuler(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha) {
    jsgppJNI.HeatEquationSolverWithStretching_solveImplicitEuler__SWIG_2(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha);
  }

  public void solveCrankNicolson(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha, long NumImEul) {
    jsgppJNI.HeatEquationSolverWithStretching_solveCrankNicolson__SWIG_0(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha, NumImEul);
  }

  public void solveCrankNicolson(long numTimesteps, double timestepsize, long maxCGIterations, double epsilonCG, DataVector alpha) {
    jsgppJNI.HeatEquationSolverWithStretching_solveCrankNicolson__SWIG_1(swigCPtr, this, numTimesteps, timestepsize, maxCGIterations, epsilonCG, DataVector.getCPtr(alpha), alpha);
  }

  public void setHeatCoefficient(double a) {
    jsgppJNI.HeatEquationSolverWithStretching_setHeatCoefficient(swigCPtr, this, a);
  }

  public void initGridWithSmoothHeat(DataVector alpha, double mu, double sigma, double factor) {
    jsgppJNI.HeatEquationSolverWithStretching_initGridWithSmoothHeat(swigCPtr, this, DataVector.getCPtr(alpha), alpha, mu, sigma, factor);
  }

  public void initScreen() {
    jsgppJNI.HeatEquationSolverWithStretching_initScreen(swigCPtr, this);
  }

  public void printGrid(DataVector alpha, long PointesPerDimension, String tfilename) {
    jsgppJNI.HeatEquationSolverWithStretching_printGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, PointesPerDimension, tfilename);
  }

  public void printGridDomain(DataVector alpha, long PointesPerDimension, BoundingBox GridArea, String tfilename) {
    jsgppJNI.HeatEquationSolverWithStretching_printGridDomain(swigCPtr, this, DataVector.getCPtr(alpha), alpha, PointesPerDimension, BoundingBox.getCPtr(GridArea), GridArea, tfilename);
  }

  public void printGridDomainStretching(DataVector alpha, long PointesPerDimension, Stretching GridArea, String tfilename) {
    jsgppJNI.HeatEquationSolverWithStretching_printGridDomainStretching(swigCPtr, this, DataVector.getCPtr(alpha), alpha, PointesPerDimension, Stretching.getCPtr(GridArea), GridArea, tfilename);
  }

  public void printSparseGrid(DataVector alpha, String tfilename, boolean bSurplus) {
    jsgppJNI.HeatEquationSolverWithStretching_printSparseGrid(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tfilename, bSurplus);
  }

  public void printSparseGridExpTransform(DataVector alpha, String tfilename, boolean bSurplus) {
    jsgppJNI.HeatEquationSolverWithStretching_printSparseGridExpTransform(swigCPtr, this, DataVector.getCPtr(alpha), alpha, tfilename, bSurplus);
  }

}
