/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class ModelFittingLeastSquares extends ModelFittingBase {
  private transient long swigCPtr;

  protected ModelFittingLeastSquares(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.ModelFittingLeastSquares_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ModelFittingLeastSquares obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_ModelFittingLeastSquares(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ModelFittingLeastSquares(FitterConfigurationLeastSquares config) {
    this(jsgppJNI.new_ModelFittingLeastSquares(FitterConfigurationLeastSquares.getCPtr(config), config), true);
  }

  public void fit(Dataset dataset) {
    jsgppJNI.ModelFittingLeastSquares_fit(swigCPtr, this, Dataset.getCPtr(dataset), dataset);
  }

  public boolean refine() {
    return jsgppJNI.ModelFittingLeastSquares_refine(swigCPtr, this);
  }

  public void update(Dataset dataset) {
    jsgppJNI.ModelFittingLeastSquares_update(swigCPtr, this, Dataset.getCPtr(dataset), dataset);
  }

  public double evaluate(DataVector sample) {
    return jsgppJNI.ModelFittingLeastSquares_evaluate__SWIG_0(swigCPtr, this, DataVector.getCPtr(sample), sample);
  }

  public void evaluate(DataMatrix samples, DataVector results) {
    jsgppJNI.ModelFittingLeastSquares_evaluate__SWIG_1(swigCPtr, this, DataMatrix.getCPtr(samples), samples, DataVector.getCPtr(results), results);
  }

}
