/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OperationEvalPartialDerivative {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OperationEvalPartialDerivative(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OperationEvalPartialDerivative obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OperationEvalPartialDerivative(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public double evalPartialDerivative(DataVector alpha, DataVector point, long derivDim, SWIGTYPE_p_double partialDerivative) {
    return jsgppJNI.OperationEvalPartialDerivative_evalPartialDerivative__SWIG_0(swigCPtr, this, DataVector.getCPtr(alpha), alpha, DataVector.getCPtr(point), point, derivDim, SWIGTYPE_p_double.getCPtr(partialDerivative));
  }

  public void evalPartialDerivative(DataMatrix alpha, DataVector point, long derivDim, DataVector value, DataVector partialDerivative) {
    jsgppJNI.OperationEvalPartialDerivative_evalPartialDerivative__SWIG_1(swigCPtr, this, DataMatrix.getCPtr(alpha), alpha, DataVector.getCPtr(point), point, derivDim, DataVector.getCPtr(value), value, DataVector.getCPtr(partialDerivative), partialDerivative);
  }

  public void setPointInUnitCube(DataVector value) {
    jsgppJNI.OperationEvalPartialDerivative_pointInUnitCube_set(swigCPtr, this, DataVector.getCPtr(value), value);
  }

  public DataVector getPointInUnitCube() {
    long cPtr = jsgppJNI.OperationEvalPartialDerivative_pointInUnitCube_get(swigCPtr, this);
    return (cPtr == 0) ? null : new DataVector(cPtr, false);
  }

}
