/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptComponentScalarFunctionHessian extends OptScalarFunctionHessian {
  private transient long swigCPtr;

  protected OptComponentScalarFunctionHessian(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptComponentScalarFunctionHessian_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptComponentScalarFunctionHessian obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptComponentScalarFunctionHessian(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptComponentScalarFunctionHessian(OptScalarFunctionHessian fHessian, DoubleVector defaultValues) {
    this(jsgppJNI.new_OptComponentScalarFunctionHessian__SWIG_0(OptScalarFunctionHessian.getCPtr(fHessian), fHessian, DoubleVector.getCPtr(defaultValues), defaultValues), true);
  }

  public OptComponentScalarFunctionHessian(OptScalarFunctionHessian fHessian) {
    this(jsgppJNI.new_OptComponentScalarFunctionHessian__SWIG_1(OptScalarFunctionHessian.getCPtr(fHessian), fHessian), true);
  }

  public OptComponentScalarFunctionHessian(OptVectorFunctionHessian fHessian, long k, DoubleVector defaultValues) {
    this(jsgppJNI.new_OptComponentScalarFunctionHessian__SWIG_2(OptVectorFunctionHessian.getCPtr(fHessian), fHessian, k, DoubleVector.getCPtr(defaultValues), defaultValues), true);
  }

  public OptComponentScalarFunctionHessian(OptVectorFunctionHessian fHessian, long k) {
    this(jsgppJNI.new_OptComponentScalarFunctionHessian__SWIG_3(OptVectorFunctionHessian.getCPtr(fHessian), fHessian, k), true);
  }

  public double eval(DataVector x, DataVector gradient, DataMatrix hessian) {
    return jsgppJNI.OptComponentScalarFunctionHessian_eval(swigCPtr, this, DataVector.getCPtr(x), x, DataVector.getCPtr(gradient), gradient, DataMatrix.getCPtr(hessian), hessian);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionHessian_t clone) {
    jsgppJNI.OptComponentScalarFunctionHessian_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__ScalarFunctionHessian_t.getCPtr(clone));
  }

}
