/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptEggholder extends OptUnconstrainedTestProblem {
  private transient long swigCPtr;

  protected OptEggholder(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptEggholder_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptEggholder obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptEggholder(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptEggholder() {
    this(jsgppJNI.new_OptEggholder(), true);
  }

  public OptTestScalarFunction getObjectiveFunction() {
    return new OptTestScalarFunction(jsgppJNI.OptEggholder_getObjectiveFunction(swigCPtr, this), false);
  }

  public double getOptimalPointUndisplaced(DataVector x) {
    return jsgppJNI.OptEggholder_getOptimalPointUndisplaced(swigCPtr, this, DataVector.getCPtr(x), x);
  }

}
