/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptG03 extends OptConstrainedTestProblem {
  private transient long swigCPtr;

  protected OptG03(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptG03_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptG03 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptG03(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptG03(long d) {
    this(jsgppJNI.new_OptG03(d), true);
  }

  public OptTestScalarFunction getObjectiveFunction() {
    return new OptTestScalarFunction(jsgppJNI.OptG03_getObjectiveFunction(swigCPtr, this), false);
  }

  public OptTestVectorFunction getInequalityConstraintFunction() {
    return new OptTestVectorFunction(jsgppJNI.OptG03_getInequalityConstraintFunction(swigCPtr, this), false);
  }

  public OptTestVectorFunction getEqualityConstraintFunction() {
    return new OptTestVectorFunction(jsgppJNI.OptG03_getEqualityConstraintFunction(swigCPtr, this), false);
  }

  public double getOptimalPointUndisplaced(DataVector x) {
    return jsgppJNI.OptG03_getOptimalPointUndisplaced(swigCPtr, this, DataVector.getCPtr(x), x);
  }

}
