/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptGaussianElimination extends OptSLESolver {
  private transient long swigCPtr;

  protected OptGaussianElimination(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptGaussianElimination_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptGaussianElimination obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptGaussianElimination(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean solve(OptSLE system, DataVector b, DataVector x) {
    return jsgppJNI.OptGaussianElimination_solve(swigCPtr, this, OptSLE.getCPtr(system), system, DataVector.getCPtr(b), b, DataVector.getCPtr(x), x);
  }

  public OptGaussianElimination() {
    this(jsgppJNI.new_OptGaussianElimination(), true);
  }

}
