/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptLeastSquaresOptimizer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected OptLeastSquaresOptimizer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptLeastSquaresOptimizer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptLeastSquaresOptimizer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void optimize() {
    jsgppJNI.OptLeastSquaresOptimizer_optimize(swigCPtr, this);
  }

  public OptVectorFunction getPhiFunction() {
    return new OptVectorFunction(jsgppJNI.OptLeastSquaresOptimizer_getPhiFunction(swigCPtr, this), false);
  }

  public long getN() {
    return jsgppJNI.OptLeastSquaresOptimizer_getN(swigCPtr, this);
  }

  public void setN(long N) {
    jsgppJNI.OptLeastSquaresOptimizer_setN(swigCPtr, this, N);
  }

  public DataVector getStartingPoint() {
    return new DataVector(jsgppJNI.OptLeastSquaresOptimizer_getStartingPoint(swigCPtr, this), false);
  }

  public void setStartingPoint(DataVector startingPoint) {
    jsgppJNI.OptLeastSquaresOptimizer_setStartingPoint(swigCPtr, this, DataVector.getCPtr(startingPoint), startingPoint);
  }

  public DataVector getOptimalPoint() {
    return new DataVector(jsgppJNI.OptLeastSquaresOptimizer_getOptimalPoint(swigCPtr, this), false);
  }

  public double getOptimalValue() {
    return jsgppJNI.OptLeastSquaresOptimizer_getOptimalValue(swigCPtr, this);
  }

  public DataMatrix getHistoryOfOptimalPoints() {
    return new DataMatrix(jsgppJNI.OptLeastSquaresOptimizer_getHistoryOfOptimalPoints(swigCPtr, this), false);
  }

  public DataVector getHistoryOfOptimalValues() {
    return new DataVector(jsgppJNI.OptLeastSquaresOptimizer_getHistoryOfOptimalValues(swigCPtr, this), false);
  }

  public void clone(SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__LeastSquaresOptimizer_t clone) {
    jsgppJNI.OptLeastSquaresOptimizer_clone(swigCPtr, this, SWIGTYPE_p_std__unique_ptrT_sgpp__optimization__optimizer__LeastSquaresOptimizer_t.getCPtr(clone));
  }

  public final static long DEFAULT_N = jsgppJNI.OptLeastSquaresOptimizer_DEFAULT_N_get();
}
