/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class OptSimionescu extends OptConstrainedTestProblem {
  private transient long swigCPtr;

  protected OptSimionescu(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.OptSimionescu_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(OptSimionescu obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_OptSimionescu(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public OptSimionescu() {
    this(jsgppJNI.new_OptSimionescu(), true);
  }

  public OptTestScalarFunction getObjectiveFunction() {
    return new OptTestScalarFunction(jsgppJNI.OptSimionescu_getObjectiveFunction(swigCPtr, this), false);
  }

  public OptTestVectorFunction getInequalityConstraintFunction() {
    return new OptTestVectorFunction(jsgppJNI.OptSimionescu_getInequalityConstraintFunction(swigCPtr, this), false);
  }

  public OptTestVectorFunction getEqualityConstraintFunction() {
    return new OptTestVectorFunction(jsgppJNI.OptSimionescu_getEqualityConstraintFunction(swigCPtr, this), false);
  }

  public double getOptimalPointUndisplaced(DataVector x) {
    return jsgppJNI.OptSimionescu_getOptimalPointUndisplaced(swigCPtr, this, DataVector.getCPtr(x), x);
  }

}
