/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public final class RegularizationType {
  public final static RegularizationType Identity = new RegularizationType("Identity");
  public final static RegularizationType Laplace = new RegularizationType("Laplace");
  public final static RegularizationType Diagonal = new RegularizationType("Diagonal");
  public final static RegularizationType Lasso = new RegularizationType("Lasso");
  public final static RegularizationType ElasticNet = new RegularizationType("ElasticNet");
  public final static RegularizationType GroupLasso = new RegularizationType("GroupLasso");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static RegularizationType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + RegularizationType.class + " with value " + swigValue);
  }

  private RegularizationType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private RegularizationType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private RegularizationType(String swigName, RegularizationType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static RegularizationType[] swigValues = { Identity, Laplace, Diagonal, Lasso, ElasticNet, GroupLasso };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

