/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SFundamentalSplineModifiedBase extends SBasis {
  private transient long swigCPtr;

  protected SFundamentalSplineModifiedBase(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SFundamentalSplineModifiedBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SFundamentalSplineModifiedBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SFundamentalSplineModifiedBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public SFundamentalSplineModifiedBase() {
    this(jsgppJNI.new_SFundamentalSplineModifiedBase__SWIG_0(), true);
  }

  public SFundamentalSplineModifiedBase(long degree) {
    this(jsgppJNI.new_SFundamentalSplineModifiedBase__SWIG_1(degree), true);
  }

  public double eval(long l, long i, double x) {
    return jsgppJNI.SFundamentalSplineModifiedBase_eval(swigCPtr, this, l, i, x);
  }

  public double evalDx(long l, long i, double x) {
    return jsgppJNI.SFundamentalSplineModifiedBase_evalDx(swigCPtr, this, l, i, x);
  }

  public double evalDxDx(long l, long i, double x) {
    return jsgppJNI.SFundamentalSplineModifiedBase_evalDxDx(swigCPtr, this, l, i, x);
  }

  public long getDegree() {
    return jsgppJNI.SFundamentalSplineModifiedBase_getDegree(swigCPtr, this);
  }

}
