/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SGetAffectedBasisFunctions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected SGetAffectedBasisFunctions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SGetAffectedBasisFunctions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SGetAffectedBasisFunctions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SGetAffectedBasisFunctions(GridStorage storage) {
    this(jsgppJNI.new_SGetAffectedBasisFunctions(GridStorage.getCPtr(storage), storage), true);
  }

  public void operatorParentheses(SLinearBase basis, DataVector point, IndexValVector result) {
    jsgppJNI.SGetAffectedBasisFunctions_operatorParentheses(swigCPtr, this, SLinearBase.getCPtr(basis), basis, DataVector.getCPtr(point), point, IndexValVector.getCPtr(result), result);
  }

}
