/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class SLinearStretchedBoundaryBase extends SLinearBoundaryBase {
  private transient long swigCPtr;

  protected SLinearStretchedBoundaryBase(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.SLinearStretchedBoundaryBase_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SLinearStretchedBoundaryBase obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_SLinearStretchedBoundaryBase(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public double stretchedEval(double p, double pos0, double pos1) {
    return jsgppJNI.SLinearStretchedBoundaryBase_stretchedEval(swigCPtr, this, p, pos0, pos1);
  }

  public double eval(long level, long index, double p, double pos0, double pos1) {
    return jsgppJNI.SLinearStretchedBoundaryBase_eval(swigCPtr, this, level, index, p, pos0, pos1);
  }

  public SLinearStretchedBoundaryBase() {
    this(jsgppJNI.new_SLinearStretchedBoundaryBase(), true);
  }

}
