/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package sgpp;

public class StratifiedSampleGenerator extends SampleGenerator {
  private transient long swigCPtr;

  protected StratifiedSampleGenerator(long cPtr, boolean cMemoryOwn) {
    super(jsgppJNI.StratifiedSampleGenerator_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StratifiedSampleGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jsgppJNI.delete_StratifiedSampleGenerator(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public StratifiedSampleGenerator(SizeTVector strataPerDimension, java.math.BigInteger seed) {
    this(jsgppJNI.new_StratifiedSampleGenerator__SWIG_0(SizeTVector.getCPtr(strataPerDimension), strataPerDimension, seed), true);
  }

  public StratifiedSampleGenerator(SizeTVector strataPerDimension) {
    this(jsgppJNI.new_StratifiedSampleGenerator__SWIG_1(SizeTVector.getCPtr(strataPerDimension), strataPerDimension), true);
  }

  public void getSample(DataVector sample) {
    jsgppJNI.StratifiedSampleGenerator_getSample(swigCPtr, this, DataVector.getCPtr(sample), sample);
  }

}
